quarto-required: ">=1.3.0"
project:
  type: website

website:
  title: "Cuerpo de Estatutos del Centro de Alumnos de Ingeniería"
  description: "Versión oficial y completa del Cuerpo de Estatutos del Centro de Alumnos de Ingeniería (CAi) de la Universidad Católica de Chioe."
  
resources:
  - CNAME

format:
  html:
    author-meta: "Centro de Alumnos de Ingeniería (CAi)"
    lang: es
    toc: true
    toc-title: Contenidos
    toc-depth: 2
    anchor-sections: true
    reference-location: section
    css: styles.css
    mainfont: Source Sans Pro
    theme:
      light: cosmo
      dark: cyborg
    
    pdf:
      lang: es
      toc: true
      toc-depth: 2
      number-sections: true
      highlight: true
      mainfont: Source Sans Pro