---
title: Cuerpo de Estatutos
subtitle: Centro de Alumnos de Ingeniería
date-modified: 2023-06-04
lang: es
format: 
  html: default
  pdf: default
---
# Estatutos

## I. Finalidades y miembros {#finalidades}

::: {#interpretacionEstatuto .art}
**Art. 1**. De la interpretación del Estatuto.

El presente estatuto se interpretará en virtud de las normas de
interpretación del Código Civil[^1].

En caso de vacío, el Comité Ejecutivo dictará un Oficio Interpretativo,
que deberá ser aprobado en sesión Ordinaria o Extraordinaria del Consejo
Generacional por mayoría absoluta. Su resolución será obligatoria desde
este caso en particular en adelante.

Este Oficio Interpretativo deberá, asimismo, anexarse al Estatuto con
todas las medidas de publicidad requeridas por éste.
:::

::: {#representacionCAi .art}
**Art. 2**. El Centro de Alumnos de Ingeniería, CAi, es un organismo que
representa a todos los alumnos de Pregrado de la Escuela de Ingeniería
de la Pontificia Universidad Católica de Chile, así como a los alumnos
de Magíster en Ingeniería, Magíster en Ciencias de la Ingeniería o
Doctorado de esta misma Unidad Académica.
:::

::: {#cultural .art}
**Art. 3**. []{#finalidadesCAi label="finalidadesCAi"} El CAi es un
organismo autónomo respecto a cualquier otra organización, tanto
estudiantil como universitaria. En esencia, el CAi debe velar por los
intereses del grupo estudiantil que representa. Para ello estructurará y
conducirá el aporte de los estudiantes de Ingeniería a la Universidad y
a la sociedad. Para cumplir este fin deberá abocarse, a través de sus
organismos directivos, a las siguientes funciones:

1.  []{#gremial label="gremial"}[En el aspecto gremial:]{.smallcaps}

    a)  Organizar, coordinar y supervisar la participación estudiantil
        en los organismos colegiados de la Universidad. Buscar medios
        para lograr una verdadera comunicación estudiantil y profesional
        de la Escuela.

2.  []{#social label="social"} [En el aspecto social:]{.smallcaps}

    a)  Lograr que el conocimiento de la realidad social del país sea
        parte fundamental en la formación de los estudiantes de
        Ingeniería.

    b)  []{#bienestar_social label="bienestar_social"} Estimular y
        apoyar actividades destinadas a lograr el bienestar social de
        los estudiantes y, en lo posible, de la comunidad en que está
        inserta.

3.  [En el aspecto cultural y de iniciativas estudiantiles:]{.smallcaps}

    a)  Promover una sólida formación cultural en el alumno y realizar
        actividades conducentes a ella.

    b)  Estimular la creación y el desarrollo de iniciativas
        estudiantiles de diversa índole, por medio de Fondos
        Concursables y apoyo directo.
:::

::: {#jerarquia .art}
**Art. 4**. []{#organismosCAi label="organismosCAi"} Los organismos
directivos del CAi son los siguientes:

1.  [Comité Ejecutivo]{.smallcaps} Encabeza al CAi. Está formado por
    ocho integrantes. En orden jerárquico, este está formado por:

    a)  Presidencia.

    b)  Vicepresidencia Interna.

    c)  Vicepresidencia Externa.

    d)  Secretaría General.

    e)  Jefatura de Finanzas.

    f)  Coordinación de Áreas.

    g)  Jefatura de Docencia.

    h)  Jefatura de Investigación.

    La Presidencia podrá ampliar el número y las funciones y
    atribuciones de los integrantes del Comité Ejecutivo dentro de sus
    propias facultades.

2.  [Consejería Académica de Pregrado, conformada por dos
    integrantes]{.smallcaps}:

    a)  Consejería Académica de Pregrado, en adelante Consejería
        Académica

    b)  Subconsejería Académica de Pregrado, en adelante Subconsejería
        Académica

3.  [Consejería Académica de Postgrado, conformada por dos
    integrantes]{.smallcaps}:

    a)  Consejería Académica de Postgrado, en adelante Consejería de
        Postgrado

    b)  Subconsejería Académica de Postgrado, en adelante Subconsejería
        de Postgrado

4.  [Comité Generacional]{.smallcaps} Está formado por tres
    representantes de cada generación, cuyo año de ingreso sea menor al
    de la quinta generación y tres representantes de la sexta o
    superior, quienes se nombran en adelante como Representantes
    Generacionales.

5.  [Comité Académico]{.smallcaps} Está formado por una persona
    representante de cada major, que debe haber inscrito el major
    respectivo y que debe estar cursando al menos la tercera generación;
    por un representante de cada departamento, centro o especialidad,
    que debe estar cursando una mención en ese departamento o realizando
    dicha especialidad, con un máximo de una representante por
    departamento o centro; por 6 representantes de postgrado, de cada
    una de las áreas del programa; y una Representante de College. Las
    áreas son las siguientes:

    a)  Ingeniería Civil (Gestión de la Construcción, Estructural y
        Geotecnia, Hidráulica y Ambiental)

    b)  Industrial y de Transporte e Instituto de Matemática

    c)  Mecánica y Metalurgia

    d)  Eléctrica

    e)  Ciencias de la Computación

    f)  Química y Bioprocesos e Instituto de Ingeniería Biológica y
        Médica

6.  [Consejo Generacional]{.smallcaps} Es la máxima instancia de
    representación. Formado por el Comité Generacional, el Comité
    Ejecutivo, la Consejería Académica y la Consejería de Postgrado. Es
    presidido por la Presidencia del CAi.

7.  [Consejo Académico]{.smallcaps} Formado por el Comité Académico, la
    Jefatura de Docencia y la Jefatura de Investigación del Comité
    ejecutivo, y las Consejerías Académicas de Postgrado y Pregrado,
    quien lo preside.

8.  [Comisiones]{.smallcaps} Las comisiones dependen del Comité
    Ejecutivo y lo ayudan en su gestión. El Comité Ejecutivo puede
    formar las comisiones que estime conveniente durante el período de
    su gestión, informando de ello a los Consejos. A modo de referencia,
    una lista sugerida de las posibles comisiones es la siguiente:

    a)  Auspicios

    b)  Comunicaciones

    c)  Comunidad

    d)  Cultura

    e)  Deportes

    f)  Docencia

    g)  Emprendimiento

    h)  Generación Novata

    i)  Política y Actualidad

    j) Proyectos

    k) Responsabilidad Social

    l) Sustentabilidad

    m) Vida Universitaria

9.  [Coordinación Generales]{.smallcaps} Alumno regular de la Escuela de
    Ingeniería que es designado por el Comité Ejecutivo para apoyar o
    liderar algún área de trabajo del CAi. La designación de uno o más
    Coordinaciones Generales debe ser informado al Consejo Generacional,
    al igual que eventuales reemplazos o renuncias. No es integrante del
    Comité Ejecutivo.
:::

::: {#funcionesEjecutivo1 .art}
**Art. 5**. Las funciones del Comité Ejecutivo son:

1.  Desarrollar una gestión de excelencia en favor del Alumnado y la
    Comunidad de la Escuela de Ingeniería, de acuerdo a lo presentado en
    su programa de postulación, de manera no vinculante. Para ello,
    podrá crear comisiones y áreas de trabajo en las que podrá nombrar y
    remover a sus respectivos Jefes de Comisión; como también podrá
    designar Coordinadores Generales.

2.  Fomentar la participación de la comunidad a través de las distintas iniciativas que surgen de esta. Para ello, designará a una     persona integrante del comité que deba encargarse de coordinar, asistir y relacionar a las distintas Iniciativas Estudiantiles CAi en las facultades que se le atribuyen a este comité.

3.  Entregar a todos los miembros del Consejo Generacional y del Consejo
    Académico una copia de los estatutos vigentes al inicio del período.

4.  Asumir la última responsabilidad de las actuaciones en las cuales
    los organismos dependientes del Comité Ejecutivo se vean
    involucrados, liberándose de esta responsabilidad al desautorizar
    públicamente y antes de que ocurra el acto que no cuenta con apoyo
    oficial.

5.  Mantener archivo oficial, redactar y despachar la correspondencia.

6.  Velar por el cumplimiento del presente cuerpo de estatutos, además
    de desarrollar sus actividades de acuerdo a los reglamentos y
    protocolos que de él emanan.
:::

::: {#funciones_presidente .art}
**Art. 6**. Las funciones y atribuciones mínimas de los miembros del
Comité Ejecutivo son las que se numeran a continuación. Esta lista no es
exhaustiva, y sin perjuicio de ella los miembros del Comité Ejecutivo
colaborarán cumpliendo con los encargos que el Presidente les
encomiende.

1.  [Presidente]{.smallcaps}

    a)  Representar al CAi y sus posturas ante las autoridades de la
        Escuela, la Universidad, la Federación y otros organismos
        pertinentes. Se considerará como postura del CAi la que adopte
        el Consejo Generacional.

    b)  Dar cuenta pública y detallada de la gestión realizada al
        término de cada semestre en ejercicio a nombre del Comité
        Ejecutivo.

    c)  Definir nuevas funciones y atribuciones a los miembros del
        Comité Ejecutivo. No podrá atribuir derechos o deberes que se
        opongan abiertamente a lo señalado en estos estatutos, o que
        superen sus propias funciones o atribuciones. Cualquier
        definición de este tipo deberá ser informada a los Consejos.

    d)  Definir la división de labores que corresponde a cada
        vicepresidente.

    e)  Dar cuenta pública, en las sesiones ordinarias del Consejo
        Generacional y del Consejo Académico, de su participación en el
        Consejo de Federación y en las instancias en las que participa
        regularmente como representante de los alumnos ante las
        autoridades de la Escuela.

2.  [Vicepresidencia Interna]{.smallcaps}

    a)  Representará al CAi en los organismos respectivos cuando el
        Presidente se lo solicitara, o cuando este faltare por motivos
        de fuerza mayor, con todas las atribuciones del cargo.

    b)  Coordinará y supervisará la labor de las comisiones y equipos de
        trabajo dependientes del Comité Ejecutivo. La división de las
        labores de los dos vicepresidentes quedará a criterio del
        Presidente en ejercicio.

3.  [Vicepresidencia Externa]{.smallcaps}

    a)  Representará al CAi en los organismos respectivos cuando el
        Presidente se lo solicitara, o cuando este faltare por motivos
        de fuerza mayor, con todas las atribuciones del cargo.

    b)  Coordinará y supervisará la labor de las comisiones y equipos de
        trabajo dependientes del Comité Ejecutivo. La división de las
        labores de los dos vicepresidentes quedará a criterio del
        Presidente en ejercicio.

4.  [Secretaría General]{.smallcaps}

    a)  Presidir y convocar las reuniones del Comité Ejecutivo y del
        Consejo Generacional. Sin perjuicio de la posibilidad de auto
        convocatoria de éste último, dispuesto en el artículo 45. En caso de no encontrarse presente, cualquier persona del Comité Ejecutivo podrá actuar en subrogancia.

    b)  Llevar control de asistencia y someter a aprobación el acta de
        cada Consejo, que se dará por aprobada mediante correo
        electrónico, a menos que un miembro del consejo se oponga. El
        plazo para oponerse será de 2 días. En caso de rechazo de la
        primera publicación del acta, existirán 3 instancias mediante
        correo electrónico para llegar a consenso sobre el acta escrita
        (entiéndase como instancia cada vez que se le envíe a los
        delegados), en caso de superar esta última, se deberá aprobar en
        el Consejo siguiente.

    c)  Publicar actas del Consejo Académico en la página web del Centro
        de Alumnos, con un plazo máximo de cinco días hábiles desde su
        aprobación por el Consejo.

    d)  Coordinar y supervisar el correcto funcionamiento de las
        comisiones, mediante la coordinación con un encargado de cada
        comisión.

    e)  Publicar las cuentas públicas de las comisiones y los delegados
        en la página del Centro de Alumnos y por otro medio que se
        considere pertinente para que llegue a los alumnos de la
        Escuela, en un plazo máximo de cinco días hábiles posterior al
        consejo en que fueron presentadas.

5.  [Jefe de Finanzas]{.smallcaps}

    a)  Administrar y llevar una cuenta de todos los ingresos y gastos
        del CAi, en la cual estos aparezcan convenientemente
        justificados y dar cuenta de ello una vez al mes en la página
        web del Centro de Alumnos, y una vez al semestre ante los
        Consejos Generacional y Académico. Con la publicación mensual de
        ingresos y gastos, se debe adjuntar la cartola mensual de la
        cuenta correspondiente a la caja chica del CAi y la glosa
        explicativa.

    b)  Dar la información que le fuese solicitada por algún miembro del
        CAi y que se refiera a la administración y finanzas.

    c)  Presentar el presupuesto anual del CAi en la sesión ordinaria de
        los Consejo Generacional y Académico correspondiente al mes de
        abril.

    d)  Presentar el estado del presupuesto anual del CAi en las
        sesiones ordinarias de los Consejo Generacional y Académico
        correspondientes al mes de julio y noviembre. En la sesión de
        noviembre, se invitará al jefe de finanzas electo para el año
        siguiente.

6.  [Coordinador de Áreas]{.smallcaps}

    a)  Gestionar los espacios de ingeniería y el préstamo de las
        propiedades del CAi.

    b)  Relacionarse con administración del campus para gestionar los
        espacios de la manera más correcta posible.

7.  [Jefe de Docencia]{.smallcaps}

    a)  Colaborar en las políticas académicas de la Escuela, trabajando
        en conjunto con el Consejero Académico.

    b)  Asistir al Comité de Pregrado.

    c)  Asistir al Consejo Académico.

8.  [Jefe de Investigación]{.smallcaps}

    a)  Integrar a las políticas académicas de la Escuela la visión de
        los alumnos de Postgrado, trabajando en conjunto con el
        Consejero Académico de Postgrado.

    b)  Asistir al Comité de Postgrado.

    c)  Asistir al Consejo Académico.

9.  [Cargos opcionales]{.smallcaps} Las funciones de los cargos
    opcionales son definidas por el Presidente, tal como se señala en la
    parte A del presente artículo.
:::

::: {#funcionesCAPregrado .art}
**Art. 7**. Las funciones y atribuciones del Consejero Académico son:

1.  Integrar a las políticas académicas de la Escuela la visión de los
    alumnos, liberando de estas responsabilidades al Presidente del CAi.

2.  Presidir el Consejo Académico.

3.  Representar a los alumnos ante el *CIDEI*, el Consejo de la Escuela
    de Ingeniería y el Comité de Pregrado, en conjunto con el Presidente
    de CAi.

4.  Estudiar y desarrollar proyectos y propuestas académicas con la
    Dirección de la Escuela y, si existiese, la Comisión de Docencia del
    CAi, preocupándose también de su difusión.

5.  Asistir a las instancias formales para las que sea llamado junto a
    sus pares de las demás facultades por el Consejero Superior FEUC,
    tales como el Consejo Académico FEUC.

6.  Dar cuenta pública, en las sesiones ordinarias del Consejo
    Generacional y Académico, de su participación en el Consejo
    Académico FEUC y en las instancias en las que participa regularmente
    como representante de los alumnos ante las autoridades de la
    Escuela.
:::

::: art
**Art. 8**. Las funciones y atribuciones del Subconsejero Académico son:

1.  Colaborar en las políticas académicas de la Escuela, trabajando en
    conjunto con el Consejero Académico.

2.  Reemplazar al Consejero Académico en el Consejo Académico FEUC,
    cuando éste no puede asistir.

3.  Reemplazar al Consejero Académico en caso de renuncia, cese
    anticipado o destitución del mismo.
:::

::: {#funcionesCAPostgrado .art}
**Art. 9**. Las funciones y atribuciones del Consejero de Postgrado son:

1.  Integrar a las políticas académicas de la Escuela la visión de los
    alumnos de Postgrado, liberando de estas responsabilidades al
    Presidente del CAi.

2.  Representar a los alumnos ante el Comité de Postgrado.

3.  Asistir a las instancias formales de representación para las que sea
    llamado por organismos atingentes a su cargo y rol.

4.  Coordinar con el Comité Ejecutivo la creación y ejecución de una
    agenda de trabajo orientada a los alumnos de Postgrado de la Escuela
    de Ingeniería.

5.  Asistir al Consejo Académico

6.  Participar en el Comité de Magíster/Doctorado según el programa al
    que pertenece (Ya sea al Comité de Magíster, si es del Magíster en
    Ciencias de la Ingeniería o al Comité de Doctorado si es del
    Doctorado en Ciencias de la Ingeniería).

7.  Sesionar a los Delegados de Postgrado una vez al mes.
:::

::: art
**Art. 10**. Las funciones y atribuciones del Subconsejero de Postgrado
son:

1.  Integrar a las políticas académicas de la Escuela la visión de los
    alumnos de Postgrado, trabajando en conjunto con el Consejero
    Académico de Postgrado.

2.  Reemplazar al Consejero de Postgrado en el Consejo Académico de
    Postgrado UC, cuando éste no puede asistir.

3.  Reemplazar al Consejero Académico en caso de renuncia, cese
    anticipado o destitución del mismo.

4.  Participar en el Comité de Magíster/Doctorado según el programa al
    que pertenece (Ya sea al Comité de Magíster, si es del Magíster en
    Ciencias de la Ingeniería o al Comité de Doctorado si es del
    Doctorado en Ciencias de la Ingeniería).
:::

::: {#representanteCollege .art}
**Art. 11**. Las funciones y atribuciones del Representante de College
son:

1.  Representar a los alumnos de College que se encuentran relacionados
    a la Escuela de Ingeniería principalmente en temas académicos.

2.  Dar cuenta pública de su gestión al menos dos veces durante su
    período a sus representados. Esta deberá ser presentada en sesión
    ordinaria del Consejo Académico y difundida por el CAi.

3.  Entregar un documento resumen al momento del cambio de mando, en
    donde se expliciten los principales proyectos llevados a cabo
    durante su periodo en ejercicio.

4.  Crear un programa de trabajo que deberá ser público al inicio de su
    gestión, y disponible en la página web del CAi a más tardar dos
    semanas después del haber asumido.
:::

::: {#cuentaPublica .art}
**Art. 12**. []{#funcionesDelegadosGeneracionales
label="funcionesDelegadosGeneracionales"} Las funciones y atribuciones
de los Delegados Generacionales son:

1.  Representar políticamente a sus compañeros.

2.  Velar por la excelencia académica de los cursos que competen a sus
    representados, principalmente aquellos de ciencias básicas y comunes
    dictados en esta u otra facultad.

3.  Para los Delegados de la primera y segunda generación, al menos uno
    de cada generación debe asistir a las sesiones del Consejo
    Académico, pudiendo alternar esta función entre más de un Delegado a
    lo largo del año académico.

4.  Al menos dos veces durante su período deberán rendir cuenta de las
    actividades realizadas a sus representados. Estas deberán ser
    difundidas por el CAi y los delegados por el medio que estimen
    conveniente.

5.  Entregar un documento resumen al momento del cambio de mando, en
    donde se expliciten los principales proyectos llevados a cabo
    durante su período en ejercicio.
:::

::: {#funcionesComiteGeneracional .art}
**Art. 13**. Las funciones y atribuciones del Comité Generacional son:

1.  Servir de puente de información e inquietudes entre el Consejo
    Generacional, la Escuela y el estudiantado.

2.  Colaborar en actividades de integración a la Escuela y generar
    instancias de participación para sus respectivas generaciones.

3.  Decidir los votos ponderados de Ingeniería para el Consejo de
    Federación los cuales son llevados al mismo por los Consejeros
    Territoriales.

4.  Colaborar en la comunicación de actividades y procesos del Comité
    Ejecutivo, además de fiscalizar su gestión.

5.  Desautorizar públicamente una actuación del Comité Ejecutivo, o
    alguno de sus miembros; del Consejero Académico y del Consejero de
    Postgrado.

6.  Formular la solicitud de destitución de su cargo a cualquier miembro
    de los organismos del CAi, por grave infracción a este estatuto o
    notable abandono de deberes.
:::

::: {#funcionesConsejoGeneracional .art}
**Art. 14**. Las funciones y atribuciones del Consejo Generacional son:

1.  Pronunciarse sobre los temas políticos que cualquiera de sus
    miembros someta a su consideración.

2.  Pronunciarse sobre los temas planteados por la Federación de
    Estudiantes de la Universidad Católica (FEUC) a través de su Consejo
    de Presidentes o cualquiera de sus instancias.

3.  Someter a plebiscito cualquier decisión que considere pertinente, en
    caso de presentarse mayoría simple del total de los votos posibles.

4.  Someter a aprobación toda consulta, elección o plebiscito que no
    contare con el quórum mínimo para su validación.

5.  Velar por el cumplimiento del presente cuerpo de Estatutos.

6.  Destituir de su cargo a todo miembro del Comité Ejecutivo que
    cumpliere con algunas de las causas establecidas como motivo de
    cesación de cargo en el presente estatuto,
    artículo [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"}.

7.  Crear comisiones de trabajo en función de la contingencia o interés
    de los miembros del Consejo Generacional. La creación de una
    comisión deberá contar con la aprobación de al menos un quinto de
    los votos totales del consejo. El rol de estas comisiones será
    recopilar información y/o elaborar propuestas para luego
    presentarlas al Consejo Generacional. Las comisiones deben estar
    formadas por al menos 4 delegados y liderada por uno de estos.
:::

::: {#funcionesDelegadosAcademicos .art}
**Art. 15**. Las funciones y atribuciones de los Delegados Académicos
son:

1.  En el caso de los Delegados de Major, canalizar los problemas
    académicos de los alumnos de su Major y de Minors asociados y
    representarlos ante las instancias académicas correspondientes. En
    el caso de los Delegados de Especialidad, canalizar los problemas
    académicos de los alumnos del segundo ciclo de formación de su
    Departamento y representarlos ante las instancias académicas
    correspondientes.

2.  Velar por la excelencia académica de los cursos que competen a sus
    representados, principalmente aquellos que son dictados en sus
    respectivas disciplinas.

3.  Representar ante el Consejo Académico a los Capítulos Estudiantiles
    y otros proyectos estudiantiles de índole académica de sus
    respectivas disciplinas.

4.  Para el caso de los delegados de especialidad, participar de las
    reuniones del departamento del cual está adscrito como
    representante.

5.  Para el caso de los delegados de major, participar del Comité de
    Programa del major respectivo, y si corresponde, participar de las
    reuniones de departamento al cual el major está adscrito.

6.  Al menos dos veces durante su período deberán rendir cuenta de las
    actividades realizadas a sus representados. Estas deberán ser
    difundidas por el CAi y los delegados por el medio que estimen
    conveniente.

7.  Entregar un documento resumen al momento del cambio de mando, en
    donde se expliciten los principales proyectos llevados a cabo
    durante su periodo en ejercicio.

8.  Para los Delegados de postgrado, al menos uno de ellos debe asistir
    a las sesiones del Consejo Generacional, pudiendo alternar esta
    función entre más de un Delegado a lo largo del año académico.
    Además, deben sesionar por lo menos una vez al mes para conversar de
    los diferentes problemas que estén surgiendo en el Programa.
:::

::: {#funcionesComiteAcademico .art}
**Art. 16**. Las funciones y atribuciones del Comité Académico son:

1.  Servir de puente de información e inquietudes entre el Consejo
    Departamental, la Escuela y el estudiantado.

2.  Colaborar en iniciativas de integración de las diferentes
    disciplinas y generar instancias para la generación de sus
    respectivas especialidades.

3.  Revisar y evaluar las políticas académicas de la Escuela. Trabajar
    junto a los Consejeros Académico y de Postgrado en la formulación de
    propuestas de mejoramiento en términos de docencia, investigación y
    extensión.

4.  Velar por el cumplimiento general de la normativa de la Escuela
    dentro de sus diferentes organismos.

5.  Desautorizar públicamente una actuación del Comité Ejecutivo, o
    alguno de sus miembros; del Consejero Académico y del Consejero de
    Postgrado.

6.  Velar por el cumplimiento del presente Cuerpo de Estatutos, tanto el
    Estatuto principal como sus Apartados.

7.  Remplazar al Consejero Académico según lo estipulado en el
    artículo [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"}.

8.  Formular la solicitud de destitución de su cargo a cualquier miembro
    de los organismos del CAi, por grave infracción a este estatuto o
    notable abandono de deberes.
:::

::: {#funcionesConsejoAcademico .art}
**Art. 17**. Las funciones y atribuciones del Consejo Académico son:

1.  Discutir y tomar postura frente a las políticas académicas de la
    Escuela o alguno de sus organismos.

2.  Pronunciarse sobre los temas académicos planteados por el Consejo
    Académico UC y por la Federación de Estudiantes de la Universidad
    Católica (FEUC) a través de su Consejo de Presidentes o cualquiera
    de sus instancias que considere correspondiente. En caso de tratarse
    de una votación del Consejo Académico UC, esta decisión no se
    considerarán los votos de los delegados de postgrado, salvo que sea
    una decisión que tenga relación con los estudiantes de postgrado.
    Esto será así mientras estos alumnos de postgrado no sean
    representados por la Federación. Si un tema es competencia de
    postgrado queda a criterio del Consejeros Académicos de Pregrado y
    Postgrado, la cual podría ser apelable por los delegados de
    postgrado.

3.  Someter a plebiscito cualquier decisión que considere pertinente, en
    caso de presentarse mayoría simple del total de los votos posibles.

4.  Someter a aprobación toda consulta, elección o plebiscito que no
    contare con el quórum mínimo para su validación.

5.  Velar por el cumplimiento del presente cuerpo de Estatutos.

6.  Destituir de su cargo a todo miembro del Consejo Académico que
    cumpliere con algunas de las causas establecidas como motivo de
    cesación de cargo en el presente estatuto,
    artículo [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"}.
:::

::: art
**Art. 18**. Las temáticas que deben ser ampliamente debatidas y
aprobadas por ambos Consejos son:

1.  Destitución de algún miembro del Comité Ejecutivo por grave
    incumplimiento de sus funciones.

2.  Modificaciones y reformas al presente estatuto de acuerdo a la parte V.

3.  Elección del Comité Ejecutivo del CAi según lo estipulado en el
    artículo [23](#eleccionesCAi){reference-type="ref"
    reference="eleccionesCAi"},
    inciso [H](#cierre){reference-type="ref"
    reference="cierre"} del presente estatuto.
:::

::: art
**Art. 19**. 16,7% de los ingresos que perciba el CAi por parte del
Decanato serán destinados al financiamiento de los Consejos Generacional
y Académico, según la siguiente repartición:

1.  10% destinado al Consejero Académico.

2.  90% a Fondos Concursables, cumpliendo lo siguiente:

    a)  Los únicos participantes serán los Delegados, y los proyectos
        deberán estar orientados a cubrir las necesidades e inquietudes
        del estudiantado.

    b)  El fondo deberá repartirse en dos períodos, según como lo
        determine el Comité Ejecutivo, con el fin de cubrir ambos
        semestres.

    c)  Las bases de los fondos concursables serán definidas por una
        comisión conformada por el Consejero Académico, el Tesorero del
        Comité Ejecutivo y un delegado correspondiente a cada Consejo
        elegido en la primera sesión ordinaria del semestre.

    d)  Las bases de los fondos concursables deberán estar en posesión
        de los delegados a más tardar un mes después a partir de la
        primera sesión ordinaria del semestre.

    e)  El jurado evaluador de los fondos concursables estará compuesto
        por el Consejero Académico, un miembro del Comité Ejecutivo
        definido por este y un miembro de cada Consejo elegido en la
        primera sesión ordinaria del semestre.

    f)  Los montos ganados se pueden utilizar hasta el último día de
        postulación del siguiente período o hasta que los Delegados que
        se hayan adjudicado los fondos cesen en su cargo.

    g)  El dinero no utilizado el primer período se sumará al monto
        destinado a fondos concursables del segundo periodo de
        postulación.
:::

::: art
**Art. 20**. Los Jefes de Comisión y sus respectivos comisionados del
CAi colaborarán con el Comité Ejecutivo en el área específica de cada
uno y participarán en las sesiones de dicho organismo en los casos y
formas que el Presidente determine.
:::

## II. Elecciones, requisitos y sanciones {#elecciones}

::: {#porcentajeMinimo .art}
**Art. 21**. Tendrán derecho a votar todos los alumnos regulares de
Pregrado de la Escuela de Ingeniería, así como los alumnos de Magíster
en Ingeniería, Magíster en Ciencias de la Ingeniería y Doctorado, salvo
cuando este estatuto específicamente indique algo distinto. Tratándose
de la elección del Comité Ejecutivo y Consejero Académico, tendrán
derecho a voto los alumnos de College de Licenciatura en Ciencias
Naturales que tengan inscrito el major de la Escuela de Ingeniería a
comienzos del segundo semestre.

Todas las elecciones y plebiscitos son válidos solo si en ellos vota al
menos el 35% de los alumnos con derecho a voto, salvo que en este
estatuto se establezca explícitamente otra cosa. En caso de no cumplirse
este quórum le corresponder a decidir al Consejo que haya llamado a
plebiscitar.
:::

::: {#definicionEleccionesYPlebiscitos .art}
**Art. 22**. Las elecciones o plebiscitos se realizarán siempre a través
de una votación universal, directa, secreta, libre e informada, de la
siguiente manera:

1.  Puede ser tanto de manera presencial como electrónica. El encargado
    de decidir esto será el Consejo que haga el llamado en la misma
    sesión en que se inicie el proceso respectivo, según acuerdo de la
    mayoría absoluta de los votos posibles. En el caso de elecciones,
    esta sesión deberá ser el día que se cierre el proceso de
    inscripción. En el caso de plebiscitos, será la misma sesión en que
    se realice el llamado a éste.

2.  Será responsabilidad del *TRICEL* organizar y salvaguardar la
    regularidad del proceso eleccionario o plebiscito, de acuerdo a lo
    estipulado en el artículo 1o del Reglamento *TRICEL*.

3.  La cuenta de votos se realizará públicamente al final del último día
    de votación. Por esto, la(s) urna(s) se guardará(n) en el CAi bajo
    llave, en el lugar que estipule el TRICEL, bajo juramento de sus
    miembros de no hacer ni permitir manipulaciones de ningún tipo.
:::

::: {#votantesCollege .art}
**Art. 23**. []{#eleccionesCAi label="eleccionesCAi"} El Comité
Ejecutivo, así como la Consejería Académica y la Consejería de
Postgrado, durarán un año en sus funciones, pudiendo ser reelegidas si
cumplieren con los requisitos. La votación de estos se realizará en una
elección que se llevará a cabo de acuerdo a las siguientes normas:

1.  El primer día hábil de octubre se abrirán las inscripciones para las
    postulaciones. Se entenderá como postulante tanto las listas
    candidatas al Comité Ejecutivo, como las candidaturas a Consejería
    Académica y Consejería de Postgrado. La apertura de inscripciones
    deberá ser avisada públicamente con una semana de anticipación. Este
    proceso de inscripción durará 10 días hábiles, con una
    preinscripción obligatoria de las candidaturas al finalizar los
    primeros 5 días hábiles del proceso.

    Las fechas podrán ser trasladadas con un margen máximo de una
    semana, previa aprobación del *Consejo Generacional* bajo quórum
    calificado.

2.  Las listas candidatas al Comité Ejecutivo podrán presentarse como
    cerradas (con los cargos previamente asignados), o abiertas (que los
    cargos se determinen de acuerdo a la votación obtenida por cada
    miembro de la lista). En el caso de presentarse una lista abierta,
    las personas que la integran deberán cumplir con lo requerido por
    los artículos [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"}
    y [25](#requisitosPresidente){reference-type="ref"
    reference="requisitosPresidente"} de esta sección.

3.  En caso de empate entre candidaturas de una lista abierta, la lista
    tendrá que dirimir el empate y entregarlo al CAi en ejercicio con un
    plazo máximo de 2 días hábiles posterior al fin del recuento de
    votos.

4.  No existe restricción con respecto al número máximo de postulantes a
    ninguna de las tres elecciones, siempre que todos cumplan con los
    requisitos estipulados en el presente estatuto.

5.  El número de personas inscritas en una lista debe corresponder, al
    menos, al número de cargos estatutarios del Comité Ejecutivo. De no
    cumplir esto, la lista no puede ser candidata al Centro de Alumnos.

6.  El proceso de preinscripción es obligatorio para todas las listas
    candidatas al Comité Ejecutivo, candidaturas a Consejería de
    Pregrado y Consejería de Postgrado, el cual consiste en:

    a)  A más tardar a las 18:00 del quinto día hábil de abierto el
        proceso, cada conjunto de postulantes debe entregar al CAi una
        lista que contenga el nombre, programa de la Escuela al que
        pertenece, generación, promedios ponderados semestrales de los
        últimos tres semestres, promedio ponderado acumulado, mail UC y
        número de créditos aprobados de cada uno de cada posible
        integrante del Comité Ejecutivo, candidaturas a Consejería
        Académica y Consejería de Postgrado. Se debe especificar el
        cargo al que postula cada persona.

    b)  El TRICEL tiene tres días hábiles, desde cerrado el proceso de
        preinscripción, para validar los requisitos de las candidaturas
        preinscritas.

    c)  Tanto el Comité Ejecutivo como las Consejerías deben ser
        postulantes que hayan aprobado el proceso de preinscripción.

    d)  Las listas no pueden ser publicadas, física ni electrónicamente,
        hasta la validación de la preinscripción por parte del TRICEL.

7.  Para inscribirse, se deberá entregar al CAi lo siguiente a más
    tardar al décimo día hábil de abierto el proceso a las 18:00 horas:

    a)  Para el Comité Ejecutivo:

        i)  La lista definitiva de postulantes, quienes deben haber
            aprobado el proceso de preinscripción. En caso de estar
            previamente asignados los cargos, estos deben ser aquí
            especificados.

        ii)  Una foto (mín. $500 \times 500$ pixeles) de cada persona
            integrante de la lista.

        iii)  El programa o plan de trabajo de la lista para su posterior
            publicación.

        iv)  Un resumen del documento anterior con largo máximo de una
            carilla tamaño oficio.

        v)  El nombre de su persona apoderada, quien no podrá ser parte
            del Comité Ejecutivo del CAi en ejercicio.

    2.  En el caso de las candidaturas a la Consejería Académica:

        i)  El nombre de la persona candidata, la cual debe haber
            aprobado el proceso de preinscripción.

        ii)  Una foto (mín. $500 \times 500$).

        ii)  Un plan de trabajo y propuestas para su período.

    3.  En el caso de las candudaturas a Consejería de Postgrado:

        i)  El nombre de la persona candidata, la cual debe haber
            aprobado el proceso de preinscripción.

        ii)  Una foto (mín. $500 \times 500$ pixeles).

        iii)  Un plan de trabajo que detalle los lineamientos, objetivos y
            propuestas para su período.

8.  []{#cierre label="cierre"}Se cerrará el proceso de inscripción diez
    días hábiles después de haber sido abierto. Si finalizado este plazo
    alguna elección no tuviera al menos dos postulantes, dicha elección
    se llevará a cabo aprobando o rechazando a la única persona
    postulante. Para que una persona postulante salga elegida bajo esta
    modalidad es necesario que lo apruebe más del 70% de los votos
    válidamente emitidos. En caso contrario las personas postulantes
    deberán ser aprobadas por ambos consejos mediante quórum calificado.

9.  Una vez cerrado el proceso de inscripción, si alguna de las listas
    debe modificar a sus candidaturas sólo puede realizar un cambio
    entre el resto de las personas integrantes de la misma. Esto podrán
    hacerlo siempre y cuando continúen cumpliendo con lo establecido en
    el inciso E.

10. En el caso de no presentarse ninguna lista dentro de ambos períodos
    de inscripción, el CAi en ejercicio continuará con sus funciones
    hasta el mes de marzo del año siguiente, mes en el que se iniciará
    un nuevo proceso eleccionario. Las fechas de dicho proceso deberán
    ser definidas en el primer consejo ordinario del Consejo
    Generacional posterior a las elecciones, siendo el último plazo para
    la realización de éstas el primer día de abril. El mismo proceso se
    seguirá en el caso de que se rechace la lista única tanto en las
    elecciones o en los Consejos, según lo estipulado en el
    artículo [23](#eleccionesCAi){reference-type="ref"
    reference="eleccionesCAi"}.

11. El Comité Ejecutivo deberá publicar en su fichero y página web los
    programas de las listas a lo más dos días hábiles después del cierre
    de inscripciones.

12. A lo más 6 días hábiles después del cierre de las inscripciones
    deberá efectuarse una asamblea general de presentación de los
    postulantes a las tres elecciones, cuyo objetivo será dar a conocer
    sus programas y responder las inquietudes del estudiantado.

13. []{#periodo label="periodo"}A lo más dos días hábiles después de la
    asamblea de presentación de las listas, se iniciará el período de
    votación, que se prolongará por dos días hábiles.

14. []{#votantes label="votantes"}Estudiantes que se encuentren cursando
    Pregrado en la Escuela de Ingeniería tendrán derecho a votar por
    Comité Ejecutivo y por Consejería Académica. Aquellos que cursen
    Postgrado en la misma tendrán derecho a votar por Comité Ejecutivo y
    por Consejería de Postgrado.

15. Estudiantes que se encuentren cursando College de Licenciatura en
    Ciencias Naturales y cumplan con lo dispuesto en el
    artículo [21](#porcentajeMinimo){reference-type="ref"
    reference="porcentajeMinimo"}, tendrán derecho a votar por Comité
    Ejecutivo y por Consejería Académica de Pregrado. Aquellos
    estudiantes que sean admisibles para votar deberán inscribirse de
    forma previa, con dos o más semanas de anticipación, para ejercer su
    voto en Ingeniería.

16. Estudiantes que cursen de forma simultánea Pregrado y Postgrado en
    la Escuela de Ingeniería podrán sufragar en una sola oportunidad,
    votando de forma simultánea al Comité Ejecutivo, Consejería
    académica y Consejería de Postgrado.

17. El resultado de las elecciones se determinará de la siguiente forma:

    a)  Si en una elección hay una sola postulación, se rige según el
        inciso [H](#cierre){reference-type="ref"
        reference="cierre"} del presente artículo.

    b)  Si hay sólo dos personas postulantes resultará elegida aquella
        que obtenga simple mayoría sobre la otra. Para estos efectos se
        entenderá que existe simple mayoría si una de las dos listas
        tiene al menos un voto más que la otra. Para estos efectos no se
        tomarán en cuenta los votos blancos ni nulos. Si ambas personas
        postulantes obtienen el mismo número de votos, le corresponderá
        decidir a los consejos Generacional y Académico por mutuo
        acuerdo.

    c)  Si hay tres o más postulantes, quienes obtengan las dos primeras
        mayorías en la votación, irán a segunda vuelta, siempre y cuando
        ninguna de ellas obtengan más del 50% de los votos válidamente
        emitidos. Se entenderá como válidamente emitidos los votos
        totales sin contar blancos ni nulos. La segunda vuelta se
        realizará a lo más 5 días hábiles después del término de la
        primera vuelta, y se regirá como una votación de sólo dos
        postulantes.
:::

::: {#requisitosEjecutivo .art}
**Art. 24**. Los postulantes al Comité Ejecutivo deberán cumplir, al
momento de la preinscripción:

1.  Ser alumnos regulares de la Escuela de Ingeniería de la Pontificia
    Universidad Católica de Chile.

2.  En el caso de alumnos de pregrado:

    a)  Tener a lo menos tres semestres cursados en la unidad académica
        o 150 créditos aprobados de algún currículum de Ingeniería Civil
        al momento de la elección.

    b)  Tener un promedio ponderado de los últimos tres Promedio
        Semestral de notas (PPS), al momento de la elección, superior o
        igual a 4,50.

        Esta norma tiene por objetivo que ningún miembro del Comité
        Ejecutivo caiga en Comisión de Permanencia durante su ejercicio.
        El organismo oficial de validación es la Dirección de Pregrado
        de la Escuela de Ingeniería.

3.  En el caso de alumnos de postgrado:

    a)  En el caso de alumnos en primer semestre del programa, cumplir
        con los requisitos establecidos para alumnos de pregrado.

    b)  En el caso de alumnos de segundo semestre en adelante, contar
        con un PPA superior o igual a 5,00.

        Esta norma tiene por objetivo que ningún miembro del Comité
        Ejecutivo caiga en Comisión de Permanencia durante su ejercicio.
        El organismo oficial de validación es la Dirección de Postgrado
        de la Escuela de Ingeniería.

4.  No haber caído en Comisión de Permanencia durante los últimos dos
    semestres efectivamente cursados.

5.  No haber acumulado dos o más alertas académicas en los últimos 3
    semestres efectivamente cursados.

6.  Tener antecedentes de probidad académica intachables.

    El TRICEL será responsable de velar por todos los incisos de este
    artículo.
:::

::: {#requisitosPresidente .art}
**Art. 25**. El candidato a Presidente del CAi deberá tener un promedio
ponderado acumulado de notas (PPA) superior o igual 4,80 y a lo menos
200 créditos aprobados de algún programa de la Escuela de Ingeniería
Civil al momento de la preinscripción.
:::

::: {#requisitosJefeInvestigacion .art}
**Art. 26**. El candidato al cargo de Jefe de Investigación deberá
específicamente ser alumno regular o en vías de grado de Postgrado.
:::

::: {#requisitosCAPregrado .art}
**Art. 27**. Los candidatos a Consejero Académico deberán cumplir con
los siguientes requisitos, al momento de la preinscripción:

1.  Ser alumno regular de algún major o título profesional de Ingeniería
    Civil con PPA superior 4.80.

2.  Haber aprobado al menos 200 créditos al momento de inscribir la
    candidatura.

3.  No haber caído en Comisión de Permanencia o haber acumulado dos o
    más alertas académicas en los últimos dos semestres efectivamente
    cursados.

4.  Tener antecedentes de probidad académica intachables. El TRICEL será
    responsable de velar por todos los incisos de este artículo.
:::

::: {#requisitosCAPostegrado .art}
**Art. 28**. Los candidatos al cargo de Consejero de Postgrado deberán
cumplir con los siguientes requisitos, al momento de la preinscripción:

1.  Ser alumno regular o en vías de grado de Postgrado con PPA superior
    5.00.

1.  Haber completado al menos un semestre en algún programa de Postgrado
    de la Escuela de Ingeniería.

3.  No haber caído en causal de eliminación.

4.  Tener antecedentes de probidad académica intachables.

    El TRICEL será responsable de velar por todos los incisos de este
    artículo.
:::

::: {#eleccionExtraordinariaCAPregrado .art}
**Art. 29**. En caso de no presentarse ningún candidato al cargo de
Consejero Académico después de los dos períodos estipulados en el
artículo [23, letra H](#cierre){reference-type="ref"
reference="cierre"} de esta parte, el Consejo Académico
elegirá de entre sus miembros (que cumplan con los requisitos de
Consejero Académico) a alguien que asuma el cargo. Esta obligación
recaerá ineludiblemente sobre alguno de los Delegados, y ellos deben
estar conscientes de dicha condición antes de ser elegidos como tales.
El Delegado que asuma el cargo tendrá la opción de designar a un
reemplazante para su labor previa como representante de especialidad.
Todas estas obligaciones corresponderán al Consejo Académico en
ejercicio.
:::

::: {#nominacionSubconsejeros .art}
**Art. 30**. La nominación de cada subconsejero se realizará posterior a
la elección de Comité Ejecutivo y Consejeros Académicos, bajo los
siguientes criterios:

1.  Para el caso del Subconsejero Académico, será el Jefe de Docencia, a
    menos que el Consejero Académico proponga una persona distinta,
    quien debe cumplir los requisitos del
    artículo [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"}.

2.  Para el caso del Subconsejero de Postgrado, este tiene que
    pertenecer al programa de Postgrado al que el Consejero de Postgrado
    no pertenece. Podría ser el Jefe de Investigación, a menos que el
    Consejero de Postgrado proponga a una persona distinta, quien debe
    cumplir con el requisito planteado anteriormente y en los
    artículos [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"}
    y [26](#requisitosJefeInvestigacion){reference-type="ref"
    reference="requisitosJefeInvestigacion"}.

3.  Ambas propuestas, deben ser validadas por mayoría simple en el
    Consejo Académico en el primer consejo ordinario de la directiva
    electa.

4.  De no ser validado, cada Consejero puede proponer otro nombre entre
    los delegados existentes que cumplan los requisitos de los
    artículos [24](#requisitosEjecutivo){reference-type="ref"
    reference="requisitosEjecutivo"} y de ser necesario el
    artículo [26](#requisitosJefeInvestigacion){reference-type="ref"
    reference="requisitosJefeInvestigacion"}.
:::

::: {#definicionesDelegados .art}
**Art. 31**. Los Delegados y el Representante de College durarán un año
en sus funciones. Esta elección se hará de acuerdo a las siguientes
normas:

1.  Para alumnos que no tengan inscrito un major o especialidad, cada
    estudiante tendrá derecho a votar por dos candidatos de su
    respectiva generación. En ningún caso podrá acumular estos dos votos
    en un mismo candidato.

2.  Para alumnos que tengan inscrito un major, cada estudiante tendrá
    derecho a votar por un candidato de su respectivo major y por dos
    candidatos de su respectiva generación. En ningún caso podrá
    acumular estos dos votos en un mismo candidato.

3.  Para alumnos que tengan inscrita una especialidad, cada alumno
    tendrá derecho a votar por un candidato de su departamento,
    especialidad o centro, además de poder votar por un candidato del
    Departamento de Ingeniería Industrial en caso que tenga inscrita una
    mención asociada a ese departamento. También deberá votar por dos
    candidatos de su respectiva generación. En ningún caso podrá
    acumular estos dos votos en un mismo candidato.

4.  Para los alumnos que tengan inscrito un major y especialidad, cada
    alumno tendrá la opción de decidir si votar por un delegado de su
    major o de su departamento, especialidad o centro. En caso de elegir
    votar por especialidad, y en caso de que el alumno tenga inscrita
    una especialidad Industrial, también podrá votar por un candidato
    del Departamento de Ingeniería Industrial.

5.  Para alumnos cursando algún programa de Postgrado, cada alumno
    tendrá derecho a votar por un candidato de su área de postgrado,
    especialidad o centro.

6.  Los alumnos que cursen de forma simultánea Pregrado y Postgrado en
    la Escuela de Ingeniería podrán sufragar en una sola oportunidad.
    Cada alumno tendrá derecho a votar por un candidato de su
    departamento, especialidad o centro, además de poder votar por un
    candidato del Departamento de Ingeniería Industrial en caso que
    tenga inscrita una mención asociada a ese departamento. También
    deberá votar por dos candidatos a delegado generacional, los cuales
    podrá repartir entre los candidatos de su respectiva generación o de
    Postgrado. En ningún caso podrá acumular estos dos votos en un mismo
    candidato.

7.  Para alumnos de College de Licenciatura en Ciencias Naturales que
    cumplan los requisitos del
    artículo [21](#porcentajeMinimo){reference-type="ref"
    reference="porcentajeMinimo"}, cada alumno tendrá derecho a votar
    por un candidato a Representante de College durante la elección de
    representantes estudiantiles de College. Es decir, el Representante
    de College será electo durante las votaciones de la facultad
    anteriormente mencionada y posteriormente ratificado por el Consejo
    Académico de la Escuela de Ingeniería.

8.  Durante la cuarta semana a partir del inicio del primer periodo
    académico para alumnos antiguos se abrirán las inscripciones para
    los postulantes. La apertura de inscripciones deberá ser avisada con
    una semana de anticipación. No existe restricción con respecto al
    número máximo de postulantes, siempre que todos cumplan con los
    requisitos estipulados en el presente estatuto. Las fechas podrán
    ser adelantadas o retrasadas con un margen máximo de dos semanas,
    previa aprobación del Consejo respectivo bajo quórum calificado.

9.  Se cerrará el proceso de inscripciones cinco días hábiles después de
    haber sido abierto. Durante estos días, los candidatos tendrán la
    obligación de entregar al CAi los siguientes documentos:

    a)  Un escrito que contenga el nombre, rut, mail UC, generación y especialidad,
        major o generación por la que postula. En el caso del
        Representante de College, deberá especificar que pertenece a
        dicho programa.

    b)  Una foto (mín. $500 \times 500$ pixeles) del candidato.

    Esta misma información deberá ser enviada por correo electrónico al
    Secretario General del Comité Ejecutivo.

10. Si sólo se hubiera presentado un candidato o ninguno para alguna
    generación, departamento, major, especialidad que no esté
    representada por un departamento o Representante de College, se
    reabrirán las inscripciones para todos los cargos durante los
    próximos cinco días hábiles para dar la posibilidad que se inscriban
    más candidatos.

11. A lo más cinco días hábiles después del cierre de las inscripciones
    se iniciará el periodo de votación, el cual se prolongará por dos
    días hábiles.

12. El resultado de las elecciones se determinará de la siguiente forma:

    a)  En el caso de los delegados Generacionales serán elegidas las
        tres primeras mayorías. Para los Delegados Académicos será
        elegida la primera mayoría de cada major, departamento y
        especialidad no representada por un departamento.\
        Tratándose del Representante de College será elegida la primera
        mayoría.

    b)  En caso de no llenarse los cupos para los distintos cargos, se
        perderá la representación correspondiente a los cargos no
        ocupados.

    c)  En caso de empate, será elegida de manera aleatoria, según el
        mecanismo libre de sesgo que el TRICEL determine, con las
        personas implicadas presentes, y con un máximo de dos días
        hábiles para realizar el sorteo e informar a ambos consejos del
        resultado.
:::

::: {#requisitosDelegados .art}
**Art. 32**. Para postular al cargo de Delegado se debe cumplir con los
siguientes requisitos:

1.  Ser alumno regular de Pregrado, de Magíster en Ciencias de la
    Ingeniería, de Magíster en Ingeniería o Doctorado de la Escuela de
    Ingeniería.

2.  Para los Delegados Generacionales:

    a)  Alumnos de pregrado: pertenecer a la generación que
        representaría y estar cursando a lo menos 30 créditos del
        currículum. Además, presentar en la oficina del CAi 50 firmas
        que validen la candidatura.

3.  Para los Delegados Académicos; en el caso de major, estar inscrito
    en el major al cual se postula como representante y estar cursando
    al menos la tercera generación; en el caso de los departamentos o
    especialidades sin departamento, estar cursando la especialidad o
    mención a la cual se postula como representante y contar con el
    grado de licenciado o estar a 30 créditos o menos de cumplirlo.
    Además el postulante, en el caso de ser alumno de pregrado, debe
    estar cursando a lo menos 30 créditos del currículum, y llevar
    realizados al menos 40 créditos o estar cursando al menos un ramo de
    la especialidad, major o mención que declara cursar. En el caso de
    los alumnos de postgrado, deben estar trabajando bajo tutela de un
    profesor en una tesis del departamento o especialidad a la cual
    postula.
:::

::: {#requisitosRepresentanteCollege .art}
**Art. 33**. Para postular al cargo de Representante de College se debe
cumplir con los siguientes requisitos:

1.  Ser alumno regular UC y poseedor de la Licenciatura de Ciencias
    Naturales y Matemáticas con un major en Ingeniería.

2.  O bien, cumplir con los siguientes requisitos:

    a)  Ser alumno regular del programa College de Licenciatura en
        Ciencias Naturales.

    b)  Encontrarse cursando como mínimo el quinto semestre en el
        programa.

    c)  Haber aprobado al menos 80 créditos de la malla de ingeniería,
        excluyendo OFG's a excepción de Habilidades Comunicativas para
        Ingenieros y Ética para Ingenieros.

    d)  Estar cursando a lo menos 30 créditos del currículum.
:::

::: {#permanencia .art}
**Art. 34**. []{#ceseCargo label="ceseCargo"} Los miembros tanto del
Consejo Académico como Generacional cesarán en sus cargos, para todos
sus efectos, por alguna de las siguientes razones:

1.  Término de su periodo.

2.  []{#alumno_regular label="alumno_regular"} Tratándose de los
    delegados, dejar de ser alumno regular de la unidad académica.

3.  []{#sin_ramos label="sin_ramos"} Tratándose de los delegados, no
    cursar ramos del currículum o dejar de trabajar bajo tutela de un
    profesor en una tesis de postgrado en un semestre dentro de su
    ejercicio.

4.  []{#destitucion label="destitucion"} Ser destituido por el Consejo
    al que pertenece por grave infracción a este estatuto.

5.  []{#renuncia label="renuncia"} Renuncia aceptada por el Presidente o
    formulada como indeclinable. Se deberá presentar la renuncia de
    forma escrita.

6.  Tratándose del Presidente, por renuncia aceptada por ambos Consejos
    o formulada como indeclinable.

7.  []{#inhabilitacion label="inhabilitacion"} Por ser inhabilitado en
    razón de su incapacidad como dirigente estudiantil. Para entender
    acogida la inhabilidad se requerirá lo siguiente:

    -   La aprobación de cada Consejo, la cual se obtendrá mediante la
        aprobación de dos tercios de los votos posibles, si se tratase
        de un miembro del Comité Ejecutivo, del Consejero Académico, o
        del Consejero de Postgrado.

    -   La aprobación de dos tercios de los votos posibles del Consejo
        al que pertenezca excluyéndose al afectado, en caso de tratarse
        de algún delegado o del Representante de College.

8.  Caer en Comisión de Permanencia.

9.  Involucrarse en situaciones de probidad académica reprochables. El
    Consejo al que pertenezca será responsable de velar por esto.

10. Asumir otro cargo de representación que integre el Consejo
    Generacional o Académico del CAi.

11. Ejercer alguno de los cargos de representación enunciados a
    continuación:

    -   Directiva de la FEUC.

    -   Consejería o Subconsejería Superior FEUC.
    
    -   Consejería Territorial FEUC.
    
    -   Delegatura CONFECh.

12. Ser elegido o ejercer algún cargo de representación estudiantil en
    otra Unidad Académica.

13. Tratándose del Representante de College, dejar de ser alumno regular
    de su unidad académica o de la Escuela de Ingeniería, asumir otro
    cargo de representación estudiantil o no cursar ramos del
    currículum.
:::

::: {#extension_ausencias .art}
**Art. 35**. []{#maxAusencias label="maxAusencias"} El número máximo de
ausencias a las sesiones del Consejo correspondiente aceptadas a los
Delegados, al Representante de College y a los representantes del Comité
Ejecutivo es como sigue:

1.  []{#ausencias_A label="ausencias_A"} Sesiones Ordinarias: Dos
    ausencias si no son justificadas, o tres ausencias si alguna de
    ellas es debidamente justificada.

    Para que una ausencia se considere justificada se debe: avisar con
    al menos 5 horas de anticipación del consejo y tener algún
    compromiso previamente establecido a la hora del consejo, o un
    evento de fuerza mayor que imposibilite asistir al consejo. Quien
    tiene el poder de validar una justificación es el Secretario General
    del Comité Ejecutivo, después de recibir el documento oficial de
    justificación. Es el Secretario quien define cómo indicar cada razón
    de justificación en el acta.

2.  []{#ausencias_B label="ausencias_B"} Sesiones Extraordinarias: un
    máximo de tres ausencias cada diez sesiones de consejos
    extraordinarios, siempre y cuando sean citados con al menos 36 horas
    de anticipación. La cantidad de ausencias se extiende en tres más
    para cada conjunto de diez Consejos Extraordinarios.\
    En el caso de los delegados de postgrado, las ausencias a aquellos
    consejos extraordinarios para decidir alguna votación ponderada de
    la FEUC no será considerada.

3.  Será posible extender la cantidad de inasistencias justificadas
    posibles para un delegado en la cantidad que el Consejo estime
    adecuado, siempre teniendo presente el contexto y los motivos. Esto
    se podrá hacer a petición del delegado después de haber perdido el
    derecho a voz y voto en el Consejo correspondiente (en el que perdió
    voz y voto). El Consejo correspondiente podrá rechazar la solicitud
    en caso de que no la considere adecuada. Esto se podrá hacer
    solamente una vez por delegado durante su período.

El tiempo mínimo que debe estar un miembro del Consejo durante una
sesión para que su asistencia sea considerada es de 30 minutos. La
asistencia de los miembros del Consejo debe ser publicada en la página
web del CAi.\
En caso de que las restricciones A o B del presente artículo sean
violadas, el Delegado será sancionado con la pérdida inmediata del
derecho a voz y voto en ambas instancias del Consejo al que pertenece
(sesiones ordinarias y extraordinarias), si bien podrá seguir
representando a los alumnos frente a los profesores de su generación,
major, departamento o especialidad, según sea el caso. En el caso del
Comité Ejecutivo, este perderá el derecho a voz y voto por el resto de
su período.\
Tratándose de los delegados generacionales de la primera y segunda
generación, se considerará como ausencia al Consejo Académico el hecho
de que ninguno de los tres esté presente. En el caso de no cumplir con
las restricciones A o B del presente artículo, se considerará que
pierden su derecho a voz y voto por el resto de su período en dicho
Consejo.
:::

::: {#ceseCargoEjecutivo .art}
**Art. 36**. Si alguno de los miembros del Comité Ejecutivo, exceptuando
al Presidente, cesare en su cargo, será reemplazado por quien designe el
Presidente, con el posible veto de alguno de los Consejos, obtenido
mediante votación por quórum calificado.
:::

::: {#ceseCargoPresidente .art}
**Art. 37**. Si fuera el Presidente el que cesare en su cargo, asumirá
el Primer Vicepresidente por lo que resta del período, efectuando una
designación del nuevo Primer Vicepresidente según lo establecido en el
artículo anterior.
:::

::: {#reemplazoDelegados .art}
**Art. 38**. Si un delegado cesare en su cargo, se designará a aquel
candidato que hubiere obtenido la siguiente mayoría no electa. En caso
de que no existiese o no aceptara, el delegado saliente tendrá la
posibilidad de proponer un reemplazante al Consejo al que pertenezca,
que deberá ser aprobado por mayoría simple. De ser rechazado, el puesto
quedará vacante. Si el delegado que cesa en su cargo hubiere perdido el
derecho a voto durante su periodo, el delegado que lo reemplazare
carecerá del mismo por toda la extensión de su periodo. Si aún lo
mantiene, mantendrá el número de ausencias del delegado saliente.
:::

::: art
**Art. 39**. Si el Representante de College cesare en su cargo, se
designará a aquel candidato que hubiese obtenido la siguiente mayoría no
electa. En caso de que no existiese o no aceptara, el Representante
saliente tendrá la posibilidad de proponer un remplazante al Consejo
Académico, el que deberá cumplir los requisitos del
artículo [33](#requisitosRepresentanteCollege){reference-type="ref"
reference="requisitosRepresentanteCollege"} y ser aprobado por mayoría
simple en el Consejo Académico. De ser rechazado el puesto quedará
vacante. Si el representante que cesa en su cargo hubiere perdido el
derecho a voto durante su periodo, el representante que lo reemplazare
carecerá del mismo por toda la extensión de su período. Si aún lo
mantiene, mantendrá el número de ausencias del Representante saliente.
:::

::: {#reemplazoCA .art}
**Art. 40**. Si el Consejero Académico cesare en su cargo, su
reemplazante será el Subconsejero Académico.
:::

::: {#cp_renuncia .art}
**Art. 41**. []{#eleccionExtraordinariaCAPostgrado
label="eleccionExtraordinariaCAPostgrado"} En caso de que el cargo de
Consejero de Postgrado quedase vacante, debe procederse como se indica a
continuación:

1.  En caso de quedar vacante por renuncia, cesación anticipada del
    cargo o deposición de un Consejero en ejercicio, su reemplazante
    será el Subconsejero de Postgrado.

2.  Si no se hubiese presentado ningún candidato al cargo de Consejero
    de Postgrado después de los dos períodos estipulados en el artículo
    [23, letra H](#eleccionesCAi){reference-type="ref"
    reference="eleccionesCAi"} de esta parte, o no hubiese una
    mayoría no electa a quién ofrecer el cargo de acuerdo a lo
    establecido en la letra A de este artículo, el Consejo Académico
    deberá solicitar al presidente del Comité Ejecutivo la elaboración
    de una lista, jerarquizada según orden de elegibilidad, de tres
    candidatos que cumplan con los requisitos establecidos para postular
    al cargo de Consejero de Postgrado. El Consejo Académico someterá a
    aprobación a los candidatos, de acuerdo al orden propuesto. Se
    ofrecerá el cargo a quién obtuviese mayoría de los votos presentes.
    Si a quién se le ofreciere el cargo no aceptase, se repetirá el
    proceso con el siguiente candidato. De no existir un candidato a
    quién ofrecer el cargo, o de haber transcurrido 3 semanas desde la
    renuncia o cesación del cargo del Consejero anterior, se declarará
    desierto el cargo por lo que reste del periodo.
:::

## III. Sesiones

### Sobre las sesiones del Comité Ejecutivo {#sobre-las-sesiones-del-comité-ejecutivo .unnumbered}

::: {#sesionesEjecutivo .art}
**Art. 42**. El Comité Ejecutivo podrá sesionar cuando lo estime
conveniente, previa notificación a todos sus miembros. Estas sesiones
serán presididas por el miembro del Comité Ejecutivo de mayor jerarquía
entre los presentes. Para esto se tendrá en cuenta la jerarquía
establecida en el artículo
[4, letra A](#jerarquia){reference-type="ref"
reference="jerarquia"}.
:::

### Sobre las sesiones de los Consejos {#sobre-las-sesiones-de-los-consejos .unnumbered}

::: {#consejos .art}
**Art. 43**. Cada Consejo debe sesionar en forma ordinaria una vez al
mes durante el año académico y de forma pública. Se entenderá el año
académico como el periodo de marzo a diciembre. El Generacional
sesionará bajo la presidencia del Presidente del Comité Ejecutivo del
Centro de Alumnos y el Académico será presidido por el Consejero
Académico.
:::

::: {#consejoOrdinario .art}
**Art. 44**. La citación a sesiones ordinarias de cada Consejo será
notificada con un mínimo de dos días hábiles de anticipación. Junto con
la citación se incluirá un borrador de la tabla con los temas a tratar.
La citación será notificada a cada miembro del Consejo vía correo
electrónico, además de ser publicada en la página web del CAi.
:::

::: {#consejoExtraordinario .art}
**Art. 45**. Cada Consejo puede ser citado en forma extraordinaria por
el Comité Ejecutivo, por un tercio de los Delegados o quién lo presida,
debiendo ser notificado a todos los miembros del consejo vía correo
electrónico con al menos 24 hrs de anticipación.
:::

::: {#sesionesPostgrado .art}
**Art. 46**. Los delegados académicos de Postgrado votarán en las
sesiones del Consejo Académico de Postgrado, llevándose los respectivos
resultados al Consejo Académico de Pregrado a través del Consejero
correspondiente.
:::

::: {#votosPostgrado .art}
**Art. 47**. Vinculado al artículo anterior, los delegados académicos de
Postgrado quedan exentos de la pérdida del derecho a voto por ausencia
en el Consejo Académico de Pregrado.
:::

::: {#facultadesPrecide .art}
**Art. 48**. La facultad de quién presida la sesión comprende:

1.  La de dirigir el debate con amplias facultades, salvo las expresas
    limitaciones consagradas en este estatuto.

2.  Amonestar a cualquier asistente que perturbare el normal desarrollo
    de la sesión. Si el amonestado persistiere en su actitud, quien
    presida el Consejo podrá expulsarlo de la sala por el resto de la
    sesión, previa aprobación del Consejo.

3.  Ordenar que abandonen la sala todos los asistentes que no fueren
    Consejeros cuando lo estimare indispensable para el normal
    desenvolvimiento de la sesión, previa aprobación del Consejo.
:::

::: {#quorumConsejo .art}
**Art. 49**. El quórum para llevar a cabo un Consejo debe ser más del
50% de los Delegados que no hayan perdido su derecho a voto. Además será
necesaria la presencia del Consejero Académico y Jefe de Docencia o
Subconsejero Académico, en el caso del Consejo Académico, y de algún
miembro del Comité Ejecutivo y del Consejero Académico, o a quien este
último haya otorgado poder, en el caso del Consejo Generacional. Pasados
los treinta minutos de la hora fijada para el comienzo de la sesión, el
quórum será de una tercera parte de los Delegados que no hayan perdido
su derecho a voto, más Consejero Académico y Jefe de Docencia o
Subconsejero Académico y de algún miembro del Comité Ejecutivo y del
Consejero Académico, o a quien este último haya otorgado poder, en el
caso del Consejo Generacional. No ocurriendo esto, se declarará
fracasada la sesión a petición de cualquier miembro del Consejo. Para el
cálculo de este quórum no se contabilizarán a los delegados de postgrado
si ellos no participan en la sesión del Consejo Académico.
:::

::: {#duracionConsejosOrdinarios .art}
**Art. 50**. Las sesiones ordinarias del Consejo durarán un módulo
académico, extensible a un máximo de dos
módulos a través de la siguiente manera:

-   Diez minutos antes del término del primer módulo, los miembros del
    Consejo que estén presentes y tengan derecho a voto, mediante
    votación simple decidirán si se extiende al segundo módulo o se cita
    a sesión extraordinaria para continuar la discusión.

-   En caso de continuar la discusión en un segundo módulo y ésta no
    finalizara, 15 minutos antes del fin de este módulo se votará, de la
    misma manera que antes, para decidir si se continúa la discusión en
    una sesión extraordinaria. Lo dispuesto en los artículos precedentes
    debe entenderse sin perjuicio del derecho del presidente a inscribir
    a los que deseen hacer uso de la palabra, limitando el tiempo de los
    oradores por acuerdo conjunto entre él y el Consejo.
:::

::: {#cuentasPublicasOrdinarias .art}
**Art. 51**. La tabla de las sesiones ordinarias de cada Consejo deberá
contemplar ---al menos--- los siguientes puntos:

1.  Cuenta del Comité Ejecutivo

2.  Cuenta del Consejero Académico

Esto sin perjuicio a la facultad de los miembros del Consejo de proponer
otros temas para la sesión, de acuerdo a lo establecido en el presente
cuerpo de estatutos.
:::

::: {#definicionTabla .art}
**Art. 52**. La tabla de cada sesión del Consejo se considerará cerrada
pasados los primeros quince minutos de iniciada la sesión. Durante este
tiempo, así como previo al inicio de la sesión, podrán proponer temas a
la tabla todos aquellos miembros del Consejo que tengan derecho a voz, y
su incorporación quedará sujeta a aprobación de quien presida la sesión.
No obstante lo anterior, una solicitud que sea apoyada por un tercio de
los miembros con derecho a voto presentes deberá ser incorporada a la
tabla sin derecho a veto posible.
:::

::: {#temaPropuestoAlumnado .art}
**Art. 53**. Si previo al inicio de una sesión de Consejo o durante los
primeros 15 minutos de ésta, el Consejo fuese requerido a discutir,
pronunciarse y/o votar en torno a un tema en particular, y dicha
solicitud viniese respaldada por la firma del 5% de los alumnos
representados por el CAi, esta solicitud deberá ser acogida e
incorporada a la tabla.
:::

::: {#fijarAsistencias .art}
**Art. 54**. En la primera sesión ordinaria de cada Consejo:

1.  Se solicitará la disponibilidad horaria de cada miembro del Consejo.
    Esta información será recopilada, de la forma que se estime
    conveniente, por el Secretario de cada consejo, quien intentará
    definir a partir de ésta el día y hora de las sesiones ordinarias
    que permitan conseguir la asistencia de la mayoría de los miembros
    del Consejo.

2.  Para el caso del Consejo Generacional se elegirá a un Secretario
    Ejecutivo, quién ocupará dicho cargo durante un semestre. Este
    tendrá el rol de apoyar al Secretario General en el funcionamiento
    del Consejo, llámese apoyo:

    a)  Levantamiento de actas, o actas resumen, en caso de Consejos
        grabados.

    b)  Coordinación y publicación de asistencias del Consejo.

    c)  Coordinación y manejo de comisiones.

    d)  Publicación de Cuentas Públicas de Comisiones y Delegados en la
        página del CAi.

    e)  Difusión de información dentro del Consejo Generacional.

3.  En la primera sesión ordinaria del Consejo Generacional se definirá
    la comisión de Fiscalización y Estatutos. Dicha comisión presentarán
    una cuenta pública dos a tres veces durante el año (teniendo como
    mínimo una cada semestre). Deberá tener, por lo menos, cinco
    delegados generacionales y un miembro del CAi. También podrán
    sumarse delegados académicos a esta comisión. La comisión será
    liderada por dos miembros de esta.
:::

::: {#cuentasPublicasSemestrales .art}
**Art. 55**. Al menos una vez al semestre, el Comité Ejecutivo, el
Consejero Académico y el Consejero de Postgrado deberán rendir una
cuenta de las labores efectuadas en el transcurso de su período.
:::

::: {#presupuestoEjecutivo .art}
**Art. 56**. En la sesión ordinaria de cada Consejo correspondiente al
mes de marzo, el jefe de finanzas del CAi deberá presentar un
presupuesto estimado para su gestión, que explicite los ingresos y
egresos esperados para el año académico. Este presupuesto debe
presentar, al menos, los gastos e ingresos estimados para cada Comisión,
así como de todo proyecto o actividad cuyo presupuesto supere 20 UF.
Este presupuesto no debe considerarse vinculante.
:::

::: {#votacioncesConsejo .art}
**Art. 57**. Toda votación se realizará de forma oral, salvo que quién
presida la sesión o la tercera parte del Consejo determine que se haga
en forma escrita, nominal y simultánea. Para efectos de votación, se
considerará lo siguiente:

1.  Tratándose del Consejo Generacional:

    -   Cada Delegado de generación tendrá un voto.

    -   El Comité Ejecutivo tendrá tres votos, correspondientes al
        Presidente y Vice-presidentes.

    -   El Consejero Académico tendrá un voto.

    -   El Consejero de Postgrado tendrá un voto.

2.  Tratándose del Consejo Académico:

    -   Cada persona delegada de major, especialidad o centro tendrá un
        voto.

    -   La persona delegada de la primera y la segunda generación que se
        encuentre representando en dicha oportunidad a su generación
        tendrá un voto.

    -   El Jefatura de Docencia del Comité Ejecutivo tendrá un voto.

    -   La Consejería Académica tendrá un voto.

    -   La Consejería de Postgrado tendrá un voto.

    -   La persona Representante de College tendrá un voto.

    -   El Subconsejería Académica tendrá un voto en caso que la
        Jefatura de Docencia no esté presente.

    -   Las personas representantes de postgrado en su conjunto tendrán
        3 votos, es ningún caso se podrá acumular más de un voto por
        representante.

3.  Para evitar la sobrerrepresentación de algún representante, en el
    caso de una votación que requiera la aprobación de ambos consejos:
    los delegados que tienen presencia en ambos Consejos sólo podrán
    votar en el Consejo al que pertenecen; los Consejeros Académicos de
    pre y postgrado sólo votarán en el Consejo Académico; y el Comité
    Ejecutivo contará solo con los votos en el Consejo Generacional.
:::

::: {#quorumMinimoVotacion .art}
**Art. 58**. El quórum mínimo para realizar cualquier votación será el
50% de los votos posibles.
:::

::: {#esquemaVotacion .art}
**Art. 59**. Toda moción sometida a votación se aprobará por simple
mayoría de los votos presentes, salvo que en este Estatuto se
especifique lo contrario. En caso de empate, la decisión final recae
sobre quién presida la sesión.
:::

::: {#quorumCalificado .art}
**Art. 60**. Las votaciones que requieran quórum calificado, serán
aprobadas por dos tercios de los votos presentes.
:::

::: {#votacionMovilizacionParo .art}
**Art. 61**. Las votaciones para decidir la participación en paros o
actividades que alteren el funcionamiento normal de la Escuela deberán
ser tomadas en el Consejo Generacional y requerirán quórum calificado de
la forma en que se especifica en este Estatuto. En caso de decidir la
participación en movilizaciones estudiantiles, estas requerirán mayoría
simple. En ambos casos, para el cálculo de este quórum no se
contabilizarán a los delegados de postgrado si ellos no participan en la
votación.
:::

::: {#votacionExterna .art}
**Art. 62**. En los casos en que los resultados de votaciones deban ser
llevados ante organismos externos al CAi, dicha votación deberá ser
llevada a cabo por el Consejo Generacional. Ésta se presentará en la
misma proporción original, redondeando al entero más cercano. Si por
este sistema se produjese un empate, se decidirá por la postura más
votada de entre las empatadas. Si el empate persistiese corresponderá dirimir a la persona quien presida el Consejo. En el caso de ser al Consejo de Presidentes de la
FEUC, o cualquier otra instancia en la que el Comité Ejecutivo tenga
derecho a voto propio, solo serán válidos los votos de los Representantes.
:::

::: {#definicionPoder .art}
**Art. 63**. Cualquier miembro del Consejo podrá delegar en otro alumno
regular de la Escuela de Ingeniería su voz y su voto para una sesión
determinada de dicho consejo mediante un poder escrito. Este poder
deberá ser entregado al Secretario antes del inicio de la sesión
correspondiente y será considerado como asistencia. En caso de que algún
Consejero o Delegado deba hacer abandono de la sesión, posterior a los
30 minutos necesarios para hacer válida la asistencia, éste podrá
sustituir su presencia mediante un poder escrito, denominado Poder de
Reemplazo. Para efecto de quórum, los poderes serán considerados como
asistencia sólo si está presente la persona a quien ha sido otorgado.
:::

::: {#maxPoderesRecividos .art}
**Art. 64**. Ningún alumno podrá acumular más de un poder a su nombre
para una misma sesión. En caso de presentarse dos o más a nombre de una
misma persona, sólo será válido el que primero haya aceptado en el curso
de la sesión.
:::

::: {#maxPoderesEmitidos .art}
**Art. 65**. Un Delegado no podrá presentar un poder más de dos veces en
su período para las sesiones ordinarias. En caso de votación en las
sesiones extraordinarias, los delegados podrán, adicionalmente a lo
anterior, dejar a lo más dos poderes simples durante su período. Esta
última cifra podrá extenderse hasta un máximo de cuatro por acuerdo del
Consejo si durante el periodo de los delegados en ejercicio se hubiese
celebrado más de diez Consejos Extraordinarios. En el caso de los
poderes de reemplazo, según el
artículo [63](#definicionPoder){reference-type="ref"
reference="definicionPoder"}, los delegados poseen un máximo de dos
poderes para sesiones ordinarios y dos para las sesiones
extraordinarias, independientes de los poderes que envían cuando no
asisten a las sesiones.
:::

### Sobre las sesiones del Consejo Generacional {#sobre-las-sesiones-del-consejo-generacional .unnumbered}

::: art
**Art. 66**. Los Consejeros Territoriales ---por la función de
representantes del alumnado de Ingeniería ante el consejo ejecutivo y de
federación que el estatuto FEUC les confiere--- son reconocidos como
participantes del Consejo Generacional sin derecho a voto, por lo cual,
no se contará su asistencia para el quórum. Se les reconocen las
siguientes facultades y derechos:

1.  Derecho a voz en las sesiones ordinarias y extraordinarias del
    Consejo Generacional.

2.  Citar al Consejo Generacional de forma extraordinaria, previo
    acuerdo de la mitad o más de los Consejeros Territoriales y
    respetando las especificaciones establecidas en este estatuto para
    ello.

3.  Proponer temas en la tabla del Consejo Generacional.
:::

### Sobre las sesiones del Consejo Académico {#sobre-las-sesiones-del-consejo-académico .unnumbered}

::: art
**Art. 67**. Para el correcto funcionamiento del Consejo Académico se
elegirá un Secretario Académico de entre los delegados. Será un cargo de
duración semestral y será elegido por mayoría absoluta de los miembros
del Consejo durante la primera sesión del Consejo y en el Consejo
Ordinario de agosto.\
Si quien fue nombrado Secretario se ausentare a una sesión, se elegirá
otro delegado que tomará acta en su lugar y deberá hacérsela llegar
dentro de dos días hábiles.\
En caso de presentar renuncia, deberá proponer a un miembro del Consejo
que lo suceda para el resto del período, sin interferir con que existan
más postulantes.\
Es responsabilidad del Secretario Académico tomar asistencia y acta
sobre las acciones que decida el Consejo, así como realizar la citación
a los consejos ordinarios y a los extraordinarios que se consideren
pertinentes.\
El acta de cada sesión deberá enviarse a todos los miembros del Consejo,
con un plazo máximo de cinco días desde su aprobación por el consejo,
además de ser publicada en la página web del Centro de Alumnos bajo
responsabilidad del Secretario General.
:::

## IV. Funcionamiento y apartados

::: {#definicionApartados .art}
**Art. 68**. Los Estatutos del Centro de Alumnos de Ingeniería pueden
ser complementados con Reglamentos y Protocolos para regular formalmente
aspectos particulares del CAi y de la vida en la Escuela. Estos
Apartados Oficiales constituirán junto a los Estatutos el denominado
Cuerpo de Estatutos, el cual funcionará de la siguiente forma:

1.  Todo Apartado deberá definirse en uno o más Artículos que se
    encontrarán bajo un titular propio en la sección Funcionamiento y
    Apartados de los Estatutos principales. Respectivamente, cada uno de
    ellos hará referencia a un documento anexo con carácter de Apartado
    Oficial.

2.  Los Estatutos deberán ser siempre publicados junto a sus Apartados.

3.  Existen dos tipos de Apartados: Los Reglamentos son una extensión de
    este Estatuto principal, por lo que deberá velarse por su
    cumplimiento de igual forma que el mismo. Los Protocolos definen
    directrices que guían el comportamiento de los Organismos del CAi.
    Su cumplimiento es fiscalizable para contribuir a una mejor gestión,
    pero por sí solo no es vinculante a un motivo de cesación del cargo
    de acuerdo al artículo
    [34](#ceseCargo){reference-type="ref"
    reference="ceseCargo"}.

4.  Los Apartados deberán ser creados y modificados según la forma
    estipulada para este caso en el artículo
    [89](#normaReforma){reference-type="ref"
    reference="normaReforma"}.

5.  Los Apartados están bajo jurisdicción de los Estatutos, en cuanto
    deben respetar y cumplir los principios y disposiciones que aquí se
    enuncian. No pueden interferir en materias básicas para las cuales
    este documento se pronuncie, en cuyo caso primará siempre lo
    señalado en los Estatutos principales.
:::

### Sobre el Tribunal Calificador de Elecciones {#sobre-el-tribunal-calificador-de-elecciones .unnumbered}

::: {#definicionTRICEL .art}
**Art. 69**. El Tribunal Calificador de Elecciones, en adelante TRICEL,
será el organismo encargado de implementar y supervisar todo proceso
eleccionario o de sufragio universal a nivel de CAi. Se regirá por un
Apartado propio denominado "Reglamento TRICEL CAi", en el cual se
especifican sus funciones y atribuciones durante los sufragios. El
TRICEL tendrá carácter temporal, cumpliendo sus funciones sólo respecto
del proceso eleccionario para el cual se constituye. Se conformará en el
siguiente momento:

1.  En el caso de elecciones de representantes del CAi, el tres días
    hábiles antes que comience el periodo de inscripción de candidatos.

2.  Para cualquier otro tipo de plebiscito, consulta directa o sufragio
    universal, lo hará en la misma sesión en que éste se convoque.
:::

::: {#funcionesTRICEL .art}
**Art. 70**. Las funciones del TRICEL son:

1.  Velar por el cumplimiento de las normas estatutarias y
    reglamentarias en el respectivo proceso eleccionario. Deberá
    discutir y aplicar su criterio para discutir ante disyuntivas que
    puedan existir.

2.  Conocer de cualquier asunto relacionado con la elección para la cual
    se constituye.

3.  Complementar lo referente a la mecánica de votación y elección en
    forma de reglamento instructivo.

4.  Determinar la lista de personas con derecho a voto de acuerdo a este
    estatuto.

5.  Distribuir el material necesario para la implementación del acto
    eleccionario y recoger el mismo, luego de realizado el acto.

6.  Atender e investigar los reclamos y observaciones presentados por
    cualquier estudiante, que haya ejercido su derecho a voto, con
    respecto a la elección.

7.  Emitir resoluciones frente a los casos o reclamos presentados para
    su fallo y conocimiento, previa deliberación de sus miembros. Las
    resoluciones serán apelables por vía de consideración ante el
    Tribunal.

8.  Calificar la elección dando su dictamen respecto de la legitimidad o
    nulidad parcial o total del acto.
:::

::: {#composicionTRICEL .art}
**Art. 71**. El TRICEL estará compuesto por los siguientes miembros:

1.  Cualquier miembro del Comité Ejecutivo, el cual será electo de la
    forma en que este lo estime conveniente. Dicho miembro presidirá el
    Tribunal.

2.  Dos delegados de cada Consejo escogidos por los delegados del
    respectivo Consejo en una sola votación. En el caso de presentarse
    un número par de listas se elegirán tres delegados del Consejo
    Generacional con el objetivo de lograr un número impar de
    integrantes del TRICEL.

3.  Los apoderados de las listas postulantes al Comité Ejecutivo si
    corresponde. Ellos deberán ser alumnos regulares. El cargo de
    miembro del TRICEL es incompatible con el de candidato a una
    elección para la cual se constituye el Tribunal.

4.  Para la elección de Comité Ejecutivo y Consejeros, un profesor de la
    Escuela, o en su defecto, uno de los representantes de postgrado
    elegido entre el Consejero de Postgrado, el Jefe de Investigación y
    Postgrado y los delegados de postgrado del Comité Académico.
:::

### Sobre iniciativas estudiantiles CAi {#sobre-iniciativas-estudiantiles-cai .unnumbered}

::: art
**Art. 72**. Se entiende por iniciativa estudiantil asociada al Centro
de Alumnos de Ingeniería como una agrupación de personas organizada, con
un mismo fin desde y/o para la comunidad de Ingeniería UC. Para que una
agrupación de estudiantes sea considerada una iniciativa estudiantil
asociada al Centro de Alumnos de Ingeniería (se hará referencia a estas
como iniciativas estudiantiles CAi) debe explicitar mediante un
documento presentado al CAi lo siguiente:

1.  Misión y visión de la iniciativa estudiantil CAi.

2.  Rol que cumple junto con su aporte a la comunidad de ingeniería y/o
    exteriores.

3.  La(s) persona(s) encargada(s) de la iniciativa estudiantil CAi, de
    los cuales al menos uno debe tener el certificado de "Alumno
    Regular" de la Escuela de Ingeniería. La persona representante
    tendrá deberes y derechos especificados en el artículo 3 y artículo
    4 del Apartado de las Iniciativas Estudiantiles CAi. Ninguno de
    ellos puede tener faltas a la ética mayores, tales y como sea
    determinado por la Dirección de Pregrado de Ingeniería (DiPre).

Todo esto estará especificado en el artículo 2 del Apartado de las
Iniciativas Estudiantiles CAi.
:::

::: art
**Art. 73**. Las especificaciones de la iniciativa estudiantil CAi
deberán ser entregadas una vez al año al Centro de Alumnos de Ingeniería
durante el mes de marzo, a más tardar una semana antes del último día
hábil del mes, incluso para iniciativas estudiantiles ya asociados al
CAi.
:::

::: art
**Art. 74**. Las especificaciones deberán ser revisadas por un miembro
del Comité Ejecutivo y un delegado de cada consejo y aprobadas o
rechazadas en un plazo de cinco días hábiles después de que se hayan
entregado las especificaciones. En caso de que estas sean rechazadas, se
le dará a la iniciativa estudiantil CAi un plazo de 2 días hábiles para
entregar un nuevo documento, el cual deberá ser revisado en los próximos
3 días hábiles. En caso de que se rechace de nuevo las especificaciones,
la agrupación de personas no será considerada como una iniciativa
estudiantil del Centro de Alumnos de Ingeniería, por lo que no podrá
participar en los presupuestos participativos. El fin de esta
verificación es tener catalogadas las iniciativas estudiantiles
asociadas al CAi con un formato completo y consistente, y no pretende
otorgar al CAi soberanía sobre las iniciativas estudiantiles CAi.
:::

### Sobre el Presupuesto Participativo {#sobre-el-presupuesto-participativo .unnumbered}

::: {#definicionPParticipativo1 .art}
**Art. 75**. El CAi debe considerar en su gestión la aplicación de la
metodología de Presupuesto Participativo, la cual consiste en asignar
recursos mediante votación directa del alumnado a iniciativas
estudiantiles CAi, como las mencionadas en el
artículo [3](#finalidadesCAi){reference-type="ref"
reference="finalidadesCAi"},
incisos [B](#social){reference-type="ref" reference="social"}
y [C](#cultural){reference-type="ref" reference="cultural"}. El
Presupuesto Participativo CAi se define de la siguiente manera:

1.  Consiste en un monto igual o mayor al 10% de los ingresos fijos que
    reciba el CAi por parte del Decanato. El Comité Ejecutivo será quien
    proponga el monto exacto, de acuerdo a lo anterior, para ser
    ratificado por mayoría absoluta del Consejo Generacional, al menos
    cinco días hábiles antes de iniciarse el proceso de inscripción.

2.  Participarán como votantes sólo los estudiantes de la Escuela de
    Ingeniería de la Pontificia Universidad Católica de Chile, según se
    definen en el artículo [21](#porcentajeMinimo){reference-type="ref"
    reference="porcentajeMinimo"}. En cuanto a las iniciativas
    estudiantiles postulantes, la mayoría de su equipo deberá cumplir
    con la condición anterior.

3.  Sin perjuicio de lo anterior, más especificaciones del proceso serán
    estipulados en el Apartado denominado *"Reglamento del Presupuesto
    Participativo CAi"*.
:::

::: {#definicionPParticipativo2 .art}
**Art. 76**. El Presupuesto Participativo CAi se asignará de acuerdo a
los resultados de una elección a realizarse simultáneamente con la de
Delegados. El proceso será análogo y paralelo al estipulado en el
artículo [31](#definicionesDelegados){reference-type="ref"
reference="definicionesDelegados"} y el dinero
será exigible por los ganadores de acuerdo a las reglas del proceso.
Para ello, serán especificados en el Reglamento del Presupuesto
Participativo los siguientes puntos:

1.  Los requisitos de postulación, tanto formales como de presentación
    de la iniciativa estudiantil CAi.

2.  Las posibles categorías y la consiguiente subdivisión del monto en
    porcentajes.

3.  Todas las iniciativas estudiantiles CAi pueden postular en este
    proceso. Si la cantidad de postulantes es menor o igual a 8, se
    aceptarán que máximo 7 iniciativas estudiantiles vayan a votación,
    en caso de que la cantidad de postulantes sea mayor o igual a 9, irá
    el 75% (aproximado al número al número entero más cercano) a
    votación. En cualquier caso, de existir pre-selección, ésta
    corresponderá a una persona del Comité Ejecutivo que debe guiarse
    por el artículo 6 y artículo 7 del Apartado de las Iniciativas
    Estudiantiles CAi.

4.  El número de iniciativas estudiantiles CAi ganadores y la forma de
    repartición de acuerdo al resultado de la elección.

5.  Las fechas, plazos y metodología para el proceso de entrega de
    informe(s) y de rendición. En cualquier caso, el proceso de
    rendición debe cerrarse antes de comenzar el mes de diciembre del
    año respectivo.
:::

::: {#sancionesPParticipativo .art}
**Art. 77**. Cualquier iniciativa estudiantil CAi ganadora que no
cumpliese con lo estipulado en el artículo
[75](#definicionPParticipativo1){reference-type="ref"
reference="definicionPParticipativo1"},
será vetado por tres años, previa aprobación por mayoría absoluta del
Consejo Generacional.\
El veto consiste en que tanto la iniciativa estudiantil CAi como las
personas registradas en su equipo no podrán volver a postular una
iniciativa estudiantil CAi en ninguno de los tres procesos siguientes.\
El Reglamento del Presupuesto Participativo contará con una sección
especial con las posibles listas iniciatives estudiantiles CAi y
personas vetadas, ordenadas por año. Al cierre de cada proceso, el
Comité Ejecutivo actualizará los nuevos listados según los ingresos y
egresos que corresponda de acuerdo a los criterios anteriores.
:::

### Sobre las Oficinas Concursables {#sobre-las-oficinas-concursables .unnumbered}

::: art
**Art. 78**. El Centro de Alumnos tiene la obligación de abrir un
proceso de postulación a las oficinas que tengan disponibles para las
iniciativas estudiantiles CAi. Esta instancia se debe iniciar una vez
que haya finalizado el proceso de presupuesto participativo, con opción
de abrirse una segunda instancia para el segundo semestre, como se
señala en el artículo 9 y 10 del Apartado de las Iniciativas
Estudiantiles CAi.

1.  Solo las iniciativas estudiantiles asociadas al Centro de Alumnos de
    Ingeniería del año presente pueden participar de este proceso.

2.  El detalle de todo el proceso está estipulado en el Apartado de las
    Iniciativas Estudiantiles CAi.

3.  La cantidad de oficinas disponibles queda sujeta al CAi del año
    presente.
:::

### Sobre Capítulos Estudiantiles {#sobre-capítulos-estudiantiles .unnumbered}

::: art
**Art. 79**. Para que una agrupación de estudiantes sea considerada un
capítulo estudiantil asociado al Centro de Alumnos de Ingeniería debe
explicitar mediante un documento presentado al CAi lo siguiente:

1.  Deben tener una misión y visión como capítulo estudiantil. Esto se
    debe alinear con actividades que considere a su respectivo
    departamento o instituto, pudiendo estas dirigirse a la comunidad de
    Ingeniería UC o a exteriores, siempre y cuando otros estudiantes de
    la Escuela puedan involucrarse.

2.  Rol que cumple con su aporte a la comunidad del departamento y/o
    exteriores, explicitando como mínimo el rol social.

3.  Declaración de los programas de primer y segundo ciclo que abarcan.

4.  Coordinación del capítulo estudiantil, de quienes al menos dos
    miembros deben estar cursando el Major o Articulación del segundo
    ciclo o licenciado del major previamente declarado y ser alumnos
    regulares de la Escuela de Ingeniería o bien alumnos de College que
    cumplan con los requisitos explicitados en el artículo 33. Ningún
    integrante de la coordinación puede tener faltas a la ética mayores,
    tales y como está determinado por la Dirección de Pregrado de
    Ingeniería (DiPre).
:::

::: art
**Art. 80**. El capítulo estudiantil deberá tener al menos un delegado
de Major y/o Especialidad electo en cada periodo como miembro activo de
la agrupación. Debe asistir a las reuniones que convoque la
coordinación.
:::

::: art
**Art. 81**. El documento al que se hace referencia en el Art. 78. del
capítulo estudiantil deberá ser entregado una vez al año al encargado de
los capítulos del Centro de Alumnos de Ingeniería a más tardar dos
semanas después de las elecciones de delegados. Esto incluye tanto a los
nuevos como actuales capítulos asociados al CAi.
:::

::: art
**Art. 82**. En caso de que delegados cesen del cargo y no queden
miembros del Consejo Académico participando en el capítulo, este dejará
de ser reconocido por el CAi hasta que un nuevo delegado asuma el cargo.
:::

::: art
**Art. 83**. Las especificaciones deberán ser revisadas por un miembro
del Comité Ejecutivo, el Consejero Académico y un delegado de cada
consejo y aprobadas o rechazadas en un plazo de cinco días hábiles
después de que se haya acabado el plazo para entregar las
especificaciones. En caso de que estas sean rechazadas, se dará al
capítulo estudiantil un plazo de 2 días hábiles para entregar un nuevo
documento, el cual deberá ser revisado en los próximos 3 días hábiles.
En caso de que se rechacen nuevamente las especificaciones, la
agrupación no será considerada como un capítulo estudiantil del Centro
de Alumnos de Ingeniería. El fin de esta verificación es tener
catalogados los capítulos asociados al CAi con un formato completo y
consistente, y no pretende otorgar al CAi soberanía sobre los capítulos.
:::

### Sobre el Protocolo Ambiental {#sobre-el-protocolo-ambiental .unnumbered}

::: {#definicionProtocoloAmbiental .art}
**Art. 84**. El Comité Ejecutivo del CAi realiza actividades y gestiones
que tienen un impacto ambiental en la comunidad que lo rodea. Por lo
mismo, deberá preocuparse de minimizar este impacto en cualquier
circunstancia, en la medida de lo posible según sus facultades y
recursos. Para guiar esta preocupación, el CAi contará con un Apartado
denominado "Protocolo Ambiental", en el cual se establecerán elementos
mínimos a considerar y cumplir.
:::

### Sobre el Protocolo de Uso de Espacios y Equipos {#sobre-el-protocolo-de-uso-de-espacios-y-equipos .unnumbered}

::: {#definicionProtocoloEspacios .art}
**Art. 85**. El Comité Ejecutivo del CAi es también responsable del buen
uso de los espacios de la comunidad de Ingeniería, lo cual ha sido
validado por la Escuela de Ingeniería. Los espacios son de la comunidad
y están disponibles para que sus miembros los utilicen, pero siempre en
respeto de los demás participantes de la misma. Para guiar el buen uso
de los espacios y la responsabilidad de asignación, el CAi contará con
un Apartado denominado "Protocolo de Uso de Espacios", en el cual se
especificará y comunicará los procesos, requisitos y plazos para la
solicitud y gestión de espacios.
:::

### Sobre el Protocolo de Transparencia {#sobre-el-protocolo-de-transparencia .unnumbered}

::: {#definicionProtocoloTransparencia .art}
**Art. 86**. El CAi es una institución que busca realizar en sus
diferentes organismos una gestión responsable y transparente con sus
representados y la comunidad en general. No se entenderá transparencia
como la publicación de información privada, sino como la preocupación
por disponer abiertamente la información de uso y beneficio público a
largo plazo.

1.  Los Delegados, Consejeros Académico y de Postgrado y el Comité
    Ejecutivo deberán publicar Cuentas Públicas dos veces en su periodo
    por medios tanto físicos como virtuales, ambos accesibles a sus
    representados. Cada una de ellas debe sintetizar respectivamente
    toda su gestión hasta el momento.

2.  En el caso del Comité Ejecutivo, deberá llevar un registro de las
    gestiones y actividades que desee llevar a cabo. En este registro
    deberá existir una preocupación por conservar la información
    relevante, tanto si es específica para sus sucesores como general
    para la comunidad. Además, deberá agregar al registro mediciones
    respecto a los resultados de estas gestiones.

Sin perjuicio de los puntos anteriores, el CAi contará con un Apartado
denominado "Protocolo de Transparencia", en el cual se especificará los
elementos, formas y criterios que guían una gestión transparente.
:::

## V. Reformas

::: art
**Art. 87**. Se deberá mantener un historial de cambios y propuestas,
tanto aprobadas como rechazadas, de los estatutos en la plataforma
GitHub (https://github.com/centro-de-alumnos-de-ingenieria/Estatutos).
La administración de este historial será responsabilidad del Secretario
General, el cual deberá usar el sistema de "pull requests" y "branches"
para mantener de manera ordenada los cambios realizados y propuestos,
detallándolos de la mejor manera posible.
:::

::: art
**Art. 88**. Estos estatutos son de carácter rígido e inapelable, es
decir, no se aceptan excepciones, solo reformas.
:::

::: {#normaReforma .art}
**Art. 89**. Cualquier posible reforma al presente Cuerpo de Estatutos
deberá seguir las siguientes normas:

1.  Deberá ser tratada, discutida y votada ampliamente en el Consejo
    Académico y el Consejo Generacional, a excepción de correcciones
    ortográficas acentuales o literal que no alteren la manera en que
    operan los estatutos, su interpretación e idea fundamental. Estas
    últimas deberán ser presentadas y explicadas en ambos consejos. En
    caso de que se presentase alguna objeción por uno o más miembros de
    cualquiera de los consejos se, deberá votar el cambio como se haría
    con cualquier otra reforma.

2.  Podrá ser presentada al Consejo Académico y al Consejo Generacional
    solo a través de miembros de él.

3.  En caso de ser los Estatutos principales, requerirá acuerdo de a lo
    menos dos tercios del total de los votos posibles del Consejo
    Académico y también del Consejo Generacional, independiente de
    ausencias o presencias. Estas reformas entrarán en vigencia a partir
    del primer día hábil del semestre académico siguiente a la
    publicación de ésta.

4.  En caso de ser un nuevo Apartado o una reforma a uno ya existente,
    requerirá acuerdo de la mayoría absoluta del total de los votos
    posibles del Consejo Académico y del Consejo Generacional. Estas
    reformas entrarán en vigencia a partir de un mes después de la
    publicación de ésta.

5.  El Secretario General tendrá la responsabilidad de publicar los
    cambios respectivos y de actualizar el presente Cuerpo de Estatutos
    a más tardar dos días hábiles una vez aprobado.
:::

[Consejo Académico y Consejo Generacional]{.smallcaps}\
Escuela de Ingeniería, Pontificia Universidad Católica de Chile\
Santiago, 18 de noviembre de 2015

[Elaborado por el Consejo de Escuela 2006]{.smallcaps}\
Fernando Zavala Guzmán, Presidente CAi UC 2006\
Felipe Herrera Barros, Consejero Académico CAi UC 2006.

[Estatutos aprobados por el Consejo de Escuela 2009]{.smallcaps}\
Pablo Varas Valenzuela, Presidente CAi UC 2009\
Sofía Undurraga Pellegrini, Consejera Académica CAi UC 2009\

[Estatutos modificados por el Consejo de Escuela 2010]{.smallcaps}\
Matías Navarro Sudy, Presidente CAi UC 2010\
Federico Rodríguez de Castro, Consejero Académico CAi UC 2010

[Estatutos modificados por el Consejo de Escuela 2011]{.smallcaps}\
Pablo Vial Birrell, Presidente CAi UC 2011\
Juan Pablo Vigneaux Ariztía, Consejero Académico CAi UC 2011\

[Estatutos modificados por el Consejo de Escuela 2012]{.smallcaps}\
Eduardo Toro Nahmías, Presidente CAi UC 2012\
María Alejandra Cuevas de la Fuente, Consejera Académica CAi UC 2012\

[Estatutos modificados por el Consejo de Escuela 2012]{.smallcaps}\
Roberto Flores Flores, Presidente CAi UC 2013\
Mariana Valle Eguren, Consejera Académica CAi UC 2013\

[Estatutos modificados por el Consejo de Escuela 2014]{.smallcaps}\
Daniel Gajardo Orellana, Presidente CAi UC 2014\
Felipe Huerta Pérez, Consejero Académico CAi UC 2014\

[Estatutos modificados por el Consejo de Escuela 2014]{.smallcaps}\
Gonzalo Jara Saba, Presidente CAi UC 2015\
Rosario Contesse Blanc, Consejera Académica CAi UC 2015\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2015]{.smallcaps}\
Gonzalo Jara Saba, Presidente CAi UC 2015\
Rosario Contesse Blanc, Consejera Académica CAi UC 2015\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2015]{.smallcaps}\
Tomás Ramírez Sarmiento, Presidente CAi UC 2016\
Joaquín Rodríguez Landaeta, Consejero Académico CAi UC 2016\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2016]{.smallcaps}\
Tomás Ramírez Sarmiento, Presidente CAi UC 2016\
Joaquín Rodríguez Landaeta, Consejero Académico CAi UC 2016\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2017]{.smallcaps}\
Josefina Calonge Gilardoni, Presidente CAi UC 2017\
Josefina Salas Kantor, Consejera Académica CAi UC 2017\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2017]{.smallcaps}\
Javiera Rivera Olivares, Presidente CAi UC 2018\
Isidora Vizcaya Soto, Consejera Académica CAi UC 2018\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2018]{.smallcaps}\
Javiera Rivera Olivares, Presidente CAi UC 2018\
Isidora Vizcaya Soto, Consejera Académica CAi UC 2018\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2018]{.smallcaps}\
Javiera Rivera Olivares, Presidente CAi UC 2018\
Isidora Vizcaya Soto, Consejera Académica CAi UC 2018\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2019]{.smallcaps}\
Paolo Fabia Vandatta, Presidente CAi UC 2019\
Ángela Parra Martinez, Consejera Académica CAi UC 2019\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2020]{.smallcaps}\
Isa Oyarzo Céspedes, Presidente CAi UC 2020\
Thomas Strauszer Caussade, Consejero Académico CAi UC 2020\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2021]{.smallcaps}\
Florencia Calvo Carvacho, Presidente CAi UC 2021\
Fernando Torres Irarrázabal, Consejero Académico CAi UC 2021\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2022]{.smallcaps}\
Karina Alarcón von Loebenstein, Presidente CAi UC 2022\
Ria Deane Takahashi, Consejera Académica CAi UC 2022\

[Estatutos modificados por el Consejo Generacional y el Consejo
Académico 2022]{.smallcaps}\
Karina Alarcón von Loebenstein, Presidente CAi UC 2022\
Ria Deane Takahashi, Consejera Académica CAi UC 2022\

[^1]: Código Civil: <http://www.leychile.cl/Navegar?idNorma=172986>
