## Oficio Interpretativo 2024 {#oi-2024}

*Emitido por Potencia CAi 2024*

**Artículos relacionados:** [Art. 34](/index.html#ceseCargo), inciso 9.

**Vacío identificado:** El Art. 34, inciso 9 establece como causal de cesación del cargo «involucrarse en situaciones de probidad académica reprochables», sin precisar qué se entiende por «reprochable» en dicho contexto.

**Interpretación:** De acuerdo con los [*Lineamientos de Gestión de Faltas a la Integridad Académica de Estudiantes de la UC*](/pdf/lineamientos-integridad-academica-uc.pdf), se entenderá como «reprochable» haber sido sancionado por cometer una falta de integridad académica de nivel:

- **Moderada:** determinada porque el estudiante tiene registro anterior de una falta similar calificada como leve.
- **Grave:** cuando se evidencia que el estudiante actúa de manera premeditada para llevar a cabo la conducta, con intención de engañar, tomando medidas para ocultar la falta cometida y/o actuando en conspiración o coludido con otros.

---
