## Oficio Interpretativo 2020 · N.º 2 {#oi-2020-2}

*Emitido por Sigma CAi 2020*

**Artículos relacionados:** [Art. 23](/index.html#eleccionesCAi), inciso 15.

**Vacío identificado:** El Art. 23, inciso 15 establece que los estudiantes de College admisibles para votar deben inscribirse con dos o más semanas de anticipación para ejercer su voto en Ingeniería, sin contemplar el caso en que el estudiante nunca haya tenido oportunidad de inscribirse previamente.

**Interpretación:** Se dará la posibilidad de que los estudiantes de College admisibles puedan inscribirse con miras a las elecciones de Centro de Alumnos y Consejería Académica 2021 hasta la semana antes de la votación, dado que no tuvieron oportunidad de hacerlo previamente.

Puntos adicionales a considerar:

1. Los estudiantes de College habilitados para votar son aquellos que tengan inscrito algún major de la Escuela de Ingeniería.
2. Para inscribirse deberán llenar un formulario y enviar documentos que acrediten su admisibilidad.
3. El formulario estaría habilitado desde el miércoles 18 al domingo 22 de noviembre.

---
