## Oficio Interpretativo 2020 · N.º 1 {#oi-2020-1}

*Emitido por Sigma CAi 2020*

**Artículos relacionados:** Art. 23, incisos 1, 8, 13 y 14.

**Vacío identificado:** El Cuerpo de Estatutos no contempla qué hacer ante una situación extraordinaria de contingencia nacional que impida llevar a cabo el proceso eleccionario en las fechas establecidas por el Art. 23, inciso 1.

**Interpretación:** Se postergará el inicio del período de inscripción de postulantes a listas de Centro de Alumnos y Consejerías Académicas de Pre y Postgrado. Los plazos relativos para los hitos posteriores del proceso (Art. 23, incisos 8, 13 y 14) se mantendrán íntegramente.

Puntos adicionales a considerar:

1. Al no tener conocimiento del proceso de elecciones FEUC, las fechas de elecciones CAi se podrán trasladar con un máximo de una semana con previa aprobación del Consejo Generacional, tal como se estipula en el Art. 23, inciso 1.
2. En caso de que se estime que no están las condiciones para poder efectuar elecciones en el presente periodo académico, se aplazarán las elecciones hasta marzo del año siguiente con previa aprobación del Consejo Generacional bajo quórum calificado.

---
