## Oficio Interpretativo 2023 {#oi-2023}

*Emitido por Hola! CAi 2023*

**Artículos relacionados:** [Art. 2](/index.html#representacionCAi), [Art. 32](/index.html#requisitosRepresentantes).

**Vacío identificado:** El Estatuto define como finalidad del CAi representar a todos los alumnos de Pregrado de la Escuela de Ingeniería, sin pronunciarse sobre la situación de la nueva Licenciatura en Ingeniería en Ciencia de la Computación, que pertenece a dicha Escuela.

**Interpretación:** Para efectos de este estatuto, el estudiantado de pregrado también considerará a estudiantes de la Licenciatura en Ingeniería en Ciencia de la Computación. Esto aplica tanto para la materia descrita en el Art. 32 sobre los requisitos para postularse al cargo de Representante, entendiéndose *ser alumno regular de Pregrado* como aquel estudiante cursante de las licenciaturas y/o títulos pertenecientes a la Escuela de Ingeniería, como para el resto de los artículos de este estatuto relativos al tema. Asimismo, se entenderá como *currículum* del alumno cualquier avance académico asociado a las distintas mallas curriculares que existen dentro de la Escuela de Ingeniería.

---
